### ISSUE TITLE
install-dkms doesn't work on Fedora 32

### ISSUE THREAD

**Issue by blackrez** [dev47apps/droidcam#115]
**Describe the bug**
I can't use install-dkms to install the module. You will find the result of  the script.

**Additional context**
(base) ➜  droidcam sudo ./install-dkms          
Webcam parameters: '640' and '480'
Adding uninstall script in '/opt/droidcam-uninstall'
Installing droidcam in /usr/bin
Installing droidcam-cli in /usr/bin
Module v4l2loopback_dc/0.0.1 already built for kernel 5.8.13-200.fc32.x86_64/4
Module v4l2loopback_dc/0.0.1 already installed on kernel 5.8.13-200.fc32.x86_64/x86_64

Marking 5.8.13-200.fc32.x86_64 (x86_64) for RPM...
copying legacy postinstall template...
Copying source tree...
rpmbuild...(bad exit status: 1)
setting SOURCE_DATE_EPOCH=1604275200
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.HQ7e4N
+ umask 022
+ cd /tmp/dkms.cGPhWV/BUILD
+ '[' '-k 5.8.13-200.fc32.x86_64 -a x86_64 --binaries-only' '!=' none ']'
++ basename v4l2loopback_dc-0.0.1.dkms.tar.gz
+ /usr/sbin/dkms mktarball -m v4l2loopback_dc -v 0.0.1 -k 5.8.13-200.fc32.x86_64 -a x86_64 --binaries-only --archive v4l2loopback_dc-0.0.1.dkms.tar.gz
Marking modules for 5.8.13-200.fc32.x86_64 (x86_64) for archiving...

Creating tarball structure to specifically accomodate binaries.

Tarball location: /var/lib/dkms/v4l2loopback_dc/0.0.1/tarball//v4l2loopback_dc-0.0.1.dkms.tar.gz

DKMS: mktarball completed.
++ basename v4l2loopback_dc-0.0.1.dkms.tar.gz
+ cp -af /var/lib/dkms/v4l2loopback_dc/0.0.1/tarball/v4l2loopback_dc-0.0.1.dkms.tar.gz v4l2loopback_dc-0.0.1.dkms.tar.gz
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.wBpsvO
+ umask 022
+ cd /tmp/dkms.cGPhWV/BUILD
+ '[' /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64 '!=' / ']'
+ rm -rf /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64
++ dirname /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64
+ mkdir -p /tmp/dkms.cGPhWV/BUILDROOT
+ mkdir /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64
+ '[' /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64 '!=' / ']'
+ rm -rf /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64
+ mkdir -p /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64//usr/src
+ mkdir -p /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64//usr/share/v4l2loopback_dc
+ '[' -d /tmp/dkms.cGPhWV/SOURCES/v4l2loopback_dc-0.0.1 ']'
+ cp -Lpr /tmp/dkms.cGPhWV/SOURCES/v4l2loopback_dc-0.0.1 /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64//usr/src
+ '[' -f v4l2loopback_dc-0.0.1.dkms.tar.gz ']'
+ install -m 644 v4l2loopback_dc-0.0.1.dkms.tar.gz /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64//usr/share/v4l2loopback_dc
+ '[' -f /tmp/dkms.cGPhWV/SOURCES/common.postinst ']'
+ install -m 755 /tmp/dkms.cGPhWV/SOURCES/common.postinst /tmp/dkms.cGPhWV/BUILDROOT/v4l2loopback_dc-0.0.1-1dkms.x86_64//usr/share/v4l2loopback_dc/postinst
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip /usr/bin/strip
+ /usr/lib/rpm/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-python-bytecompile /usr/bin/python 1 0
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
Processing files: v4l2loopback_dc-0.0.1-1dkms.noarch
warning: Deprecated external dependency generator is used!
Finding  Provides: /usr/lib/dkms/find-provides
Finding  Requires(interp): 
Finding  Requires(rpmlib): 
Finding  Requires(verify): 
Finding  Requires(pre): 
Finding  Requires(post): 
Finding  Requires(preun): 
Finding  Requires(postun): 
Finding  Requires(pretrans): 
Finding  Requires(posttrans): 
Finding  Requires: /usr/lib/rpm/find-requires
Finding  Conflicts: 
Finding  Obsoletes: 
Finding  Recommends: 
Finding  Suggests: 
Finding  Supplements: 
Finding  Enhances: 
Provides: v4l2loopback_dc = 0.0.1-1dkms
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Requires(preun): /bin/sh
Requires: /usr/bin/sh
error: Arch dependent binaries in noarch package

RPM build errors:
    Deprecated external dependency generator is used!
    Arch dependent binaries in noarch package
Error! There was a problem creating your rpm.

**Comment by carlhoerberg** [comment]
Worked fine in fedora 33
