### ISSUE TITLE
can not change height to anything else then 480; though in the browser all resolutions are available

### ISSUE THREAD

**Issue by Tzahreddin** [dev47apps/droidcam#124]
I followed the instructions on https://www.dev47apps.com/droidcam/linux/

the width of the image i can change to different settings form 176 up to 4160 but the height stays at 480 (in combination with the droidcam client on linux). If i use the browser then different other resolutions are available and the height is appropriate to the witdth. 

I'm using ubuntu 20.04 with kernel 5.4.0-58 with a Nokia 8 phone via Wifi connection with DroidCamX running.

Please feel free to ask for more details, if necessary.

Best Thomas

**Comment by aramg** [comment]
Hi, please use email for support questions (email is listed in the app store and on Twitter).
You can set whatever value you want to height parameter, could you explain in your email what you mean by it says at 480?
