### ISSUE TITLE
Website: Add GitHub links & checksums & other marketing

### ISSUE THREAD

**Issue by Ethanol6** [dev47apps/droidcam#126]
I think it would be nice to see more obvious GitHub links on the Dev47 website. I only found one link on the linux page labelled "source". There should be one on the front page I think. It might help bring people here.

Also, can checksums get added to the website somewhere?

Is this project open source? I think it should say so on the website. Linux people love that.

**Comment by aramg** [comment]
I used to have the checksum on the website but found it de-syncs during updates with the CDN, requiring a cache flush as an extra step. I added it back in.

As for more prominent Github links, for now that's on purpose to try and keep noise levels down with support related GitHub issues. For now, only the Linux client is open source.
