### ISSUE TITLE
Rotation (linux)

### ISSUE THREAD

**Issue by inspire1989** [dev47apps/droidcam#128]
Hi!
I just bought the Android app and installed the Linux v4l2loopback_dc tool for it and it works really great - thanks!
Though Microsoft Teams doesn't work when I rotate the camera image as described by swapping width and height. This just leads to a black screen... The droidcam-cli interface supports mirroring but sadly no rotation. I'd really appreciate to have a rotation option in future :)

Thanks!
Martin

**Comment by AvverbioPronome** [comment]
> Microsoft Teams doesn't work

I have the same problem, people online seem convinced that Teams isn't too happy when the webcam resolution is over 720p (or even 720p)

**Comment by inspire1989** [comment]
Oh good hint, thanks! Reducing the resolution to 480x640 (rotated) works with MS Teams :)

**Comment by aramg** [comment]
This is the 2nd report now that MS Teams works at max 720p.
@inspire1989 can this issue be closed then? I know it's not a true rotation but doing it any other way isn't realistic right now due to the lack of simple graphics libraries on Linux.

**Comment by inspire1989** [comment]
MS Teams works on 720p without rotation but with rotation enabled, 480x640 is the maximum that was working for me ;)
yes this issue can be closed :) Thanks!

**Comment by AvverbioPronome** [comment]
> people online seem convinced

I say this because on linux I have been unable to make them work. Maybe because I have to set the resolution from v4l2loopback as well as .config/droidcam -- just using the second doesn't do it for me. (Or maybe because snap gets in the way)

**Comment by aramg** [comment]
It sounds like MS Teams problem. I have had reports it does not work at regular 1080p, but it worked ok at 720.
So they may be limiting the video width to 720 pixels.
