### ISSUE TITLE
NDI protocol support

### ISSUE THREAD

**Issue by nowak-mariusz** [dev47apps/droidcam#130]
I am using droidcam on Linux and droidcam-obs on MacOS, particularly for work related video calls (MS Teams). While the Linux version is perfectly fine for my needs I find the Mac setup too heavy: the need to keep OBS in background is a little disturbing and the additional enconding on my Macbook forces it to run heavy on CPU (no GPU encoding possible) and the result is a constant noise coming from Macbook fans running at full speed. Tried with lower resolutions with mild results.

Recently I stepped into an alternative: NDI HX camera (paid, but older version is available widely on the web) with NDI Virtual Input (free) installed on my Macbook, available for Windows too. It fixed my main issue - no more noise since there is no middle encoding step - MS Teams is ready to consume the stream incoming, this was a much relief! Also I find the NDI easier to setup since it automatically detects any sources available at the local network - no more static IPs configuration needed. While it looks great on a first glance I notice few disadvantages: the mobile app is expensive and it keeps my screen on all the time, also it's not possible to use my phone in the meantime (I used scrcpy to browse my phone while it served as webcam - impossible with HX Camera).

Is it possible to have the NDI protocol supported in Droidcam or droidcam-obs?

**Comment by aramg** [comment]
On the list for DroidCam OBS, yes.
Will keep this open.

**Comment by aramg** [comment]
NDI support has been released as https://tallis.live
