### ISSUE TITLE
v4l2loopback is causing my microphone and headphones to make crackling noises

### ISSUE THREAD

**Issue by Jullegaming04** [dev47apps/droidcam#131]
When i use Droidcam or Droidcam OBS my microphone is cutting, clipping and making crackling noises. I have a Yeti X wich should not make those sounds but when i start Droidcam or Droidcam OBS it is starting to make crackling noises

https://youtu.be/UjKL9krznms

**Comment by aramg** [comment]
Hi, v4l2loopback with strictly a video driver and should not interfere with audio, if it is then its a bug with the Yeti/its drivers.

Did you enable audio support for the regular droidcam app (`./install-sound`)? 
See if 'snd-aloop' is present any of these files
/etc/modprobe.d/droidcam.conf
/etc/modules-load.d/droidcam.conf
/etc/modules

delete the lines with snd-aloop and reboot the computer to disable the ALSA loopback driver, which is the more likely problem.

Support email is on the Play Store, I'm closing this issue as off-topic.
