### ISSUE TITLE
Query available MJPEG stream resolutions

### ISSUE THREAD

**Issue by moppman** [dev47apps/droidcam#132]
I'm running DroidCamX and I'm accessing the MJPEG stream that is offered by the app under `http://<ip:port>/video` with ffmpeg.
I'm aware that we can request a specific video resolution via GET request, e.g. `http://<ip:port>/video?1920x1080`. 
My question: is there a way to query all available resolutions?
I noticed that, e.g., a GET request for `?480x640` (portrait mode) still returns a 640x480 resolution, so I'd like to know which parameters are actually available.
Thanks!

**Comment by aramg** [comment]
Merged with #140
