### ISSUE TITLE
Switch "-dev=" for choice of video source not working (linux)

### ISSUE THREAD

**Issue by osering** [dev47apps/droidcam#133]
Hello!
I am using just droidcam-client with v4l2loopback-dkms_0.12.5 (and not included v4l2loopback-ds). I have more than one virtual video sources and trying to use "-dev=/dev/videoX" switch to make droidcam-cli use one of them.
That does not work and droidcam grabs only the first one. For instance, I have /dev/video11 as "OBS Source", and /dev/video12 as "PhoneCam". Command 'droidcam-cli adb 4747 -a -w -size=1920x1080 -dev=/dev/video12' still connects to /dev/video11.

Problem arises as also OBS26 inbuilt "Virtual Camera" starter is not configurable (previous addon v4l2sink was much better in this respect) and also grabs first virtual video device /dev/video11. Therefore there is a collision and impossibility to use droidcam together with OBS Studio and probably other tools with virtual cams implementations.

As OBS Studio (linux) is very popular opensource project and tool, such thing deters its' users from using opensource drodcam and makes using closedsource IriunWebcam.

P.S. I could not find -dev= switch implementation in linux droidcam gui as well.

**Comment by aramg** [comment]
As per `droidcam-cli` usage, you need to specify options before device id and port
```
Usage: 
 ./droidcam-cli [options] adb <port>
   Connect via adb to Android device
```

Also `-w` is invalid, should be `-v`
