### ISSUE TITLE
90 degrees counter-clockwise rotation

### ISSUE THREAD

**Issue by Pourliver** [dev47apps/droidcam#134]
**Describe the bug**
If I am streaming my cellphone's camera in a portait position, the camera is sideways on Linux. It is not possible to rotate the camera 90 degrees counter-clockwise.

**Expected behavior**
If I am streaming my cellphone's camera in a portait position, I expect the camera to be in a portait position on Linux.

**Additional context**
I tried the mirroring / vertical options, inversing width/height, but this only achieved 90 degrees clockwise rotation.

**Comment by aramg** [comment]
Did you see the note on Video rotation under the Install section here:
https://www.dev47apps.com/droidcam/linux/

Its a pseudo-rotation, but thats the only current available option on Linux.
