### ISSUE TITLE
Using the app enables some kind of 'phone mode' that can't be disabled in the settings.

### ISSUE THREAD

**Issue by Sir-Fenrir** [dev47apps/droidcam#136]
**Describe the bug**
I am using a Bluetooth headset with my phone, and when I open the app, it gets triggered into the phone call mode, meaning that all other sources of sound are ignored. This means I can no longer connect my headset to my phone while I use it as a webcam and actually hear people in calls at the same time.

**Expected behavior**
I expect it not to enable a phone mode or at least offer an option to disable this.

**Additional context**
My headset is connected to two sources (phone and PC), and both are now ignored as sound input.

**Comment by aramg** [comment]
Just pushed a new update out that wraps all the new bluetooth code under an option in the Settings.
Should become available globally on the Play Store in next 2-3 days.

**Comment by Sir-Fenrir** [comment]
Thank you for your quick response! I'll test it out when it's available and then I'll close this issue :)

**Comment by Sir-Fenrir** [comment]
I can confirm that it works, thank you for your work!

**Comment by enra64** [comment]
Btw, I can also confirm that this works, but I had to toggle Bluetooth SCO Link from off->on->off before it really seemed to be off and my headset no longer went into headset mode. Maybe the default is set up the wrong way around? Also, a description of what SCO means would be nice in the app :wink: Thanks for the app, btw.

**Comment by aramg** [comment]
TBH I'm not even 100% sure what the SCO thing is :)
I've had test phones where bluetooth headsets "just worked", some where the SCO mode made it work, and I've had crash reports from people trying to enable SCO (against the Android docs). 
It's very inconsistent across the board, and my experience with bluetooth overall has never been good.

Here are some links that may help though:
http://gopinaths.gitlab.io/post/bluetooth_sco_android/
https://developer.android.com/reference/android/media/AudioManager#startBluetoothSco()
