### ISSUE TITLE
System audio "popping" on Linux

### ISSUE THREAD

**Issue by wlw-codes** [dev47apps/droidcam#137]
**Describe the bug**
After connecting to my phone using DroidCam on Linux Mint 20.1 (Kernel 5.4.0-65), I experience audio "popping" sounds across all applications.

**Expected behavior**
There are no audio popping issues.

**Additional context**
The audio popping does not stop after disconnecting and closing DroidCam, only after a reboot.

**Comment by aramg** [comment]
Is the audio pop-ing coming from the speakers? Could you give some more details.
DroidCam uses the Linux ALSA loopback driver, it should be possible for it create system wide glitches like that. I am afraid this is system/kernel issue based on your initial comment.

**Comment by wlw-codes** [comment]
Apologies for my late reply, I have been busy with school.

I recorded my screen while listening to a copyright free song on YouTube. It has been edited to play a slightly longer clip first, then it repeats the exact part that the "popping" occurs at, then it plays it slowed down so you can hear the audio artifacts better. [Here](https://user-images.githubusercontent.com/31250645/107280258-fe84aa80-6a4f-11eb-8a2a-1829236f8048.mp4) is a link to that video (hosted on githubusercontent.com).

To be clear, the artifacts occur throughout all system audio, not just on YouTube or in Brave web browser. They do not occur until I have opened DroidCam and connected to my Android phone via USB. They continue after disconnecting and closing DroidCam. They only stop upon a reboot of my machine.

Please let me know if there's any more information I can provide to hopefully fix this issue.

**Comment by aramg** [comment]
Unfortunately I have to blame this on the system.
DroidCam uses the Linux kernel loopback driver, it does not interfere or modify any audio settings on its own.
Did you make an ALSA config changes, to setup the DroidCam mic?

**Comment by wlw-codes** [comment]
I have made changes to try and fix the artifact issue, though the DroidCam-related issue had occurred before I did that. I haven't installed the ALSA loopback sound card by running `./install-sound`, perhaps I should try that and see if the issues still occur.

**Comment by wlw-codes** [comment]
Didn't fix it! Must be a system issue. I'll reopen this issue if I ever manage to fix it and post my solution. Thanks for the help!
