### ISSUE TITLE
REST api for Camera control

### ISSUE THREAD

**Issue by rwebber** [dev47apps/droidcam#140]
I have DroidCam feeding into an video art piece I am working on. (thank-you!)
However, I would like to control the camera (zoom in and out, AutoFocus etc..) via http get calls.
I tried a few that I found in the webapp, such as http://IP:4747/cam/1/af
or http://IP:4747/cam/1/zoomout
I have seen the camera respond once to each, but I can't get it to do some reliably.
Is this something that should be possible?
If not would you consider making a control REST api?

**Comment by aramg** [comment]
The original API is really basic, you need to make those HTTML while the camera is active.
Each call has to use its own connection, eg. `curl http://IP:4747/cam/1/zoomout`
 ```
/cam/1/af
/cam/1/led_toggle
/cam/1/zoomout
/cam/1/zoomin
```

The new DroidCam OBS app has a better API, if you want to consider looking into it.
The remote control web-page is not obfuscated if you pull up it's source.

**Comment by rwebber** [comment]
Thanks for the reply, this should be rather helpful.
I imagine was running into problems with individual connections. 
I will double check that each connection closes.
Thanks again.

**Comment by aramg** [comment]
Adding https://github.com/dev47apps/droidcam/issues/132 here
