### ISSUE TITLE
Have Droidcam-Cli parameter that launches it without trying to read stdin

### ISSUE THREAD

**Issue by JohSchillerEmnify** [dev47apps/droidcam#141]
My notion would be that the Implementation should be fairly straightforward, adding a check before invoking `wait_command()` that checks if a `-nocontrols` flag has been set, and skipping that part if true.   But since I'm not too sure at which point this is checked, I don't know if it's really as easy as I think it is.

I would be very greatful for feedback on the Idea, if it's too complicated or you don't have the time right now I would be interested in contributing that feature if possible.

something along the lines of 
``` 
 if (argv[i][0] == '-' && argv[i][1] == 'nocontrols') { #not too sure on syntax here since index is probably used here maybe use a single symbol as parameter
     nocontrols = 1;
     continue;
 }
```
and then 
in main 

``` 
if  (!nocontrols) { #not too sure on the syntax here
    wait_command()
}
```
or maybe reverse that by initializing a variable `controls` with value 1  and checking  `if (controls)` ?

**Comment by aramg** [comment]
Sure, a `-nocontrols` option that wraps `wait_command()` is fair enough, I would accept that PR.

I would do (since 'nocontrols' is a longer word)
```
if (argv[i][0] == '-' && strstr(&argv[i][1], "nocontrols") != NULL)

**Comment by JohSchillerEmnify** [comment]
Hi, as per your suggestion I've now opened a pullrequest for this. Feel free to let me know if I should change anything additionally! Thank you for your time!

**Comment by aramg** [comment]
LGTM!
