### ISSUE TITLE
droidcam audio with PipeWire or without pulseaudio

### ISSUE THREAD

**Issue by sispus** [dev47apps/droidcam#142]
Hi,
Now I am using pipewire instead of pulseaudio on Manjaro KDE. It is possible with pipewire to use pulseaudio apps and some of its commands, however pacmd is not one of them.
Is there a way to connect droidcam audio to computer without pulseaudio?

**Comment by saknl** [comment]
I'm interested in this too. Fedora 34 is going to replace pulseaudio with pipewire as well.

**Comment by aramg** [comment]
I think this is a question for pipewire/Manjaro/KDE/Fedora. There are too many distros and too many frequent changes for me to keep up with. 

Droidcam uses the kernel loopback driver (snd_aloop), which should be consistent across all Linux based system.

**Comment by sispus** [comment]
I can "create" a loopback card and record sound from android phone via droidcam (using audacity, for example).  However, I don't have a "source" to redirect sound to a sink. With pacmd command, I could see my phone as a source, but pipewire doesn't have that command (or module?). I cannot find a way to create a source/device to manage using pavucontrol, etc.. (Sorry I don't know the exact terminology)

**Comment by aramg** [comment]
Yep, makes sense. I would expect if distros are moving away from pulseaudio to pipewire, then there must be an equivalent in pipewire. Manjaro/Fedora help forums will be the quickest way to figure it out.
I can help with Ubuntu issues, as thats the distro I know/use.

**Comment by saknl** [comment]
The solution was posted on the pipewire gitlab: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/713
You just have to select the right input profile in pavucontrol. For me it works on Fedora. It's even easier than than pulseaudio, because you don't need to use `pacmd load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio` anymore.

**Comment by ErickTucto** [comment]
I have the same problem, it seems that there is only support for alsa and not for pipewire

in this screenshot you can see the list of input devices and there is no Droidcam
![imagen](https://user-images.githubusercontent.com/22831024/146591858-b7c5938f-2704-44a4-a0d3-2396c64f6ba6.png)

However, if I use simplescreenrecorder I can choose by alsa the input device created by Droidcam
![imagen](https://user-images.githubusercontent.com/22831024/146592257-ef464f69-53c7-4c49-ae41-e731625da6c6.png)

When I go to Google Meet, Zoom, Facebook, etc. It does not show me the input device created by DroidCam

Here I show you an example with Google Meet, you can't see the Droidcam input device
![imagen](https://user-images.githubusercontent.com/22831024/146592980-c36706b1-2006-412a-b8de-23086c7cc6ff.png)

Sorry, my system is configured in the Spanish language
