### ISSUE TITLE
No rule to make target 'modules'.

### ISSUE THREAD

**Issue by Magicrafter13** [dev47apps/droidcam#149]
**Describe the bug**
`install-video` is unable to complete successfully.  
Output:
```
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/tmp/droidcam/v4l2loopback'
make -C /lib/modules/5.9.16-1-MANJARO/build M=/tmp/droidcam/v4l2loopback modules
make[1]: Entering directory '/usr/lib/modules/5.9.16-1-MANJARO/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.9.16-1-MANJARO/build'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/tmp/droidcam/v4l2loopback'
```

**Expected behavior**
`make` builds correctly.

**Additional context**
Operating System is Manjaro Linux (obviously, based on the output).

Is 'modules' supposed to be some kind of built in target or something? Because it's quite literally just not in the Makefile...

**Comment by aramg** [comment]
'modules' is supposed to be a target in `/lib/modules/5.9.16-1-MANJARO/build` (part of Linux, kernel-headers package AFAIK).
Either something has changed with Linux v5.9, or you are missing `linux-headers-$(uname -r)`

**Comment by Magicrafter13** [comment]
> 'modules' is supposed to be a target in `/lib/modules/5.9.16-1-MANJARO/build` (part of Linux, kernel-headers package AFAIK).
> Either something has changed with Linux v5.9, or you are missing `linux-headers-$(uname -r)`

I was hoping that it being able to cd into that directory, implied the headers were installed.
Manjaro's package repositories do not contain any packages that start with linux-headers, so using the suggested approach of `linux-headers-$(uname -r)` will not work.
```
$ sudo pacman -S linux-headers-$(uname -r)
error: target not found: linux-headers-5.9.16-1-MANJARO
```

**Comment by aramg** [comment]
Well, according to https://forum.manjaro.org/t/root-tip-get-droidcam-working-on-manjaro/1233 
```
$ mhwd-kernel -li  
Currently running: 5.7.4-1-MANJARO (linux57)
The following kernels are installed in your system:
   * linux56
   * linux57

$ sudo pacman -Syu linux56-headers linux57-headers
```
is the equivalent on Manjaro.

**Comment by Magicrafter13** [comment]
Ah, that did it, thanks.

(Also, I won't open a new issue, since this doesn't seem "issue-worthy", and I've got everything I wanted working, but; on my system, despite libjpeg-turbo being installed, it is not installed to `/opt` even though I did install it from the package manager.)
