### ISSUE TITLE
Verify Size / Resolution Settings handling with higher resolutions

### ISSUE THREAD

**Issue by Gambloide** [dev47apps/droidcam#150]
**Describe the bug**
Using standard `v4l2loopback` the droidcam `1.7.1` application on Linux ignores the size settings in `~/.config/droidcam`. In fact, it overwrites the given values to `0x0` with each start of the application.

The droidcam-cli `1.7.1` also often ignores the size parameter, e.g. `droidcam-cli -size=3840x2160 adb 4747`
The specific resolution doesn't matter, you can also use `1920×1080` to reproduce it.

I got it to work **sometimes**, only when carrying out the following steps in this specific order:

1. Establish a droidcam-cli connection via adb, e.g. via `droidcam-cli -size=3840x2160 adb 4747`
2. Close the connection in the Android app via the `Stop` button
3. Close the Android application
4. Close the droidcam-cli with `ctrl+c`
5. Open the Android application again
6. Start droidcam-cli with e.g. `~/.config/droidcam`

**Expected behavior**
Giving the size parameters via `droidcam-cli size` or in `~/.config/droidcam` is not ignored.

**Additional context**
The phones is a Samsung Galaxy S9 Edge Plus capable of capturing 4k video @ 60fps.
The video quality is set to high in DroidCamX.
The free DroidCam version is not installed.
CamDroidX is set to USB only mode.
The Android camera application is also set to capture video in 4k@60fps.
The problem exists both ways, once I get the app to stream with a specific resolution by chance it is also a struggle to get it back to a lower resolution again, e.g. 1080p -> 480p.
This situation is especially annoying in my case, as I have the phone firmly mounted and cannot interact with the screen.

**Comment by aramg** [comment]
The app is limited to 1080p, as noted in the Play Store and the website.
There is a note on 4K video on the help page: https://www.dev47apps.com/droidcam/help/

**Comment by Gambloide** [comment]
It doesn't matter if you use 4k or other resolutions. I only used it as an example and only tried it because even getting the stream from 480p to 1080p reliably also didn't work. 

> The specific resolution doesn't matter, you can also use 1920×1080 to reproduce it.

> The problem exists both ways, once I get the app to stream with a specific resolution by chance it is also a struggle to get it back to a lower resolution again, e.g. 1080p -> 480p.

**Comment by aramg** [comment]
Seems to work as expected for me.
Could you

1. Run droidcam-cli with any size <= 1080p. ex `./droidcam-cli -size=1280x720 <target> <port>`
2. Paste the output from ` ffprobe /dev/video0 2>&1 | grep Stream` 
(where videoX is the standard v4l2loopback device)
Ex:
```
$ ffprobe /dev/video1 2>&1 | grep Stream
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 331776 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k

**Comment by Gambloide** [comment]
Thanks for the pointer!

I did that and played around with it a bit.
It seems like the culprit was OBS Studio.

When I keep OBS Studio running with the video capture device as a source, the changes in resolution are ignored, even when the resolution is set to "Leave Unchanged".

Once I closed OBS, any resolution I chose was applied without any problem.

While this is fine for me personally, since I now know how to work around this, I suppose there would be value in a warning being logged/shown when this problem occurs on the client side.

**Comment by aramg** [comment]
Thats just how v4l2loopback works. Maybe there is a way to determine if its already open on the other side.

The DroidCam version of v4l2loopback uses a pre-configured, fixed, resolution to make it more deterministic.
[You can try it instead](https://github.com/dev47apps/droidcam#v4l2-loopback-webcam-driver) as well.
