### ISSUE TITLE
Face Tracking

### ISSUE THREAD

**Issue by Maingron** [dev47apps/droidcam#152]
I'd like to have a feature that follows your face / crops the area down to your face. With that it could maybe be possible that the phone records in 4k, crops into your face and streams 1080p to the PC.
I'd really appreciate such feature since I can't really find a way that allows me to do it live on the PC to use it in a online meeting or livestream, for example.

This should also include the following configuration options:
- How close to crop into the face
- How quick / stable (quick would mean more jitter while stable would mean slower but more stable tracking)

Maybe there could also be a setting to disable / dim the stream or display a placeholder image when no face is detected.

**Comment by aramg** [comment]
Closing this as not planned for this client. 

You can try OBS Studio along with the [DroidCam OBS app/plugin](https://dev47apps.com/obs/) and the [Face Tracker plugin](https://obsproject.com/forum/resources/face-tracker.1294/)
