### ISSUE TITLE
Mobile Data and Audio Only Mode

### ISSUE THREAD

**Issue by ineverknew-omni** [dev47apps/droidcam#155]
This is regarding the droidcam-obs-plugin for my specific use case, but could be implemented on all versions. Forgive me if this is the wrong place but I couldn't find where to add an issue on the relevant github page.

In view of the increasing availability of 5G and use of unlimited data contracts, would it be possible to implement the use of mobile data instead of wifi/usb. I see this only becoming more useful in the future!

An audio only mode for droidcam-obs-plugin would also be very useful for me, especially if it could significantly reduce mobile data usage if both features were to be implemented. Maybe an option to always prevent video on mobile data mode would be useful!
(I saw the previous issue regarding the audio only mode for the regular droidcam client so I presume that has been implemented, but I haven't used this version so I don't know for sure).

Thanks!

**Comment by aramg** [comment]
Hi, thanks for the feedback. I'm closing this, but noting down your suggestions.

It's tricky to do it over 5G because carriers put restrictions on the networks for security reasons.
The app would need to work more like https://obs.ninja, which is definitely an option down the line.
