### ISSUE TITLE
Remember connection type

### ISSUE THREAD

**Issue by edent** [dev47apps/droidcam#156]
**Describe the feature you'd like to see added to the app**
I use USB (Android) mode. Whenever I restart the app, it returns to WiFi/LAN mode.

Is there a way to get the app to default to the previously used connection?

Thanks!

**Comment by aramg** [comment]
The last connection type should be saved & restored, the settings file is `~/.config/droidcam`.
Can you check if that file is present

**Comment by edent** [comment]
It is! I was using two different logins on my machine. Thanks!
