### ISSUE TITLE
gdk error: extended controls button not working

### ISSUE THREAD

**Issue by flortsch** [dev47apps/droidcam#157]
**Describe the bug**
Pressing the extended controls button does not open the controls menu (Zoom +/-, Auto Focus, ...).

**Expected behavior**
Pressing the extended controls button should open the controls menu (Zoom +/-, Auto Focus, ...).

**Additional context**
Running Droidcam on Gnome 40.0 under Wayland session.
On the console, the following error is shown when pressing the button:

```
(droidcam:4356): Gdk-CRITICAL **: 19:16:30.129: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```

Starting Droidcam with x11 gdk backend circumvents this: `GDK_BACKEND=x11 droidcam`

**Comment by aramg** [comment]
Assuming this was due to #197.

Please feel free to comment if the issue is still present.
