### ISSUE TITLE
Tray Icon/Widget

### ISSUE THREAD

**Issue by boi4** [dev47apps/droidcam#159]
Hello,
I am a big fan of Droidcam!

A feature that would be great is the usage of the droidcam application in a system tray bar application mode, similar to networkmanager-applet and redsshift-gtk.

I imagine a small droidcam icon in the status bar. If you click the icon, a small dropdown window appears with autofocus/zoom etc options.

This is especially useful during a conference call as the status bar widget would be less intrusive and more comfortable to use.

Thank you!

**Comment by aramg** [comment]
The client had this, but the old AppIndicator apparently is getting deprecated and was removed in Debian.
https://github.com/dev47apps/droidcam/releases/tag/v1.7.1
https://askubuntu.com/questions/1273411

**Comment by SuperJC710e** [comment]
+1 for a tray icon. 

We're not all on debian. Also, the tray icon still works on even some distant debian derivatives. Work around for now is to download version 1.7 from the releases page. A more fully featured tray app would also be appreciated!

Thanks for the app!

**Comment by ptrkc** [comment]
Other desktop environments still use it and one of the most popular gnome extensions is one that adds AppIndicator support back into gnome. I would appreciate it if it could be added back into the client. Thank you very much for your work.

**Comment by aramg** [comment]
I'm with you all, the Debian removal so far seems to have only caused problems, I wouldn't be surprised if they go back on the decision.

https://github.com/dev47apps/droidcam/releases/tag/v1.7.3

**Comment by aramg** [comment]
Closing/Merging this into #182
