### ISSUE TITLE
Select /dev/video<NR> number by parameter

### ISSUE THREAD

**Issue by lpinilla** [dev47apps/droidcam#161]
Whenever I start droidcam, it creates a virtual camera on /dev/video2 by default.

I want to be able to change the video id by parameter, something like:

droidcam --custom_video_id 3 that would remap to /dev/video3

Thanks for your time

**Comment by aramg** [comment]
You can specify video_nr in `/etc/modprobe.d/droidcam.conf`

options v4l2loopback_dc width=640 height=480 video_nr=3

**Comment by lpinilla** [comment]
does the /dev/video3 interface should already be created or the program will create it itself?

**Comment by aramg** [comment]
Everything under /dev is created by the system, you should not have to touch anything there.

The number from /etc/modprobe.d/droidcam.conf will be using during system startup.
You can do it manually like this
```
sudo rmmod v4l2loopback_dc
sudo insmod /lib/modules/`uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko width=640 height=480 video_nr=3
```
