### ISSUE TITLE
bash: ./droidcam: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by dhanshreeee** [dev47apps/droidcam#166]
bash: ./droidcam: cannot execute binary file: Exec format error

I get this error. Please some tell how to fix it asap.
![image](https://user-images.githubusercontent.com/55548422/117010644-9f5ecb00-ad0a-11eb-8321-4f7e70dc5fd6.png)

**Comment by aramg** [comment]
It seems you're trying to run the x64 binary from the download package.
See https://github.com/dev47apps/droidcam/wiki/Raspberry-PI on how to build droidcam for the Pi

**Comment by dhanshreeee** [comment]
So how do i fix this? I had tried the same site for installing

**Comment by siyandaV-0** [comment]
With a Raspberry pi, you have to download the `source code` version of the release:
With the current latest version for example:

```
 $ wget https://github.com/dev47apps/droidcam/archive/refs/tags/v1.8.2.zip
 $ unzip v1.8.2.zip 
 $ cd droidcam-1.8.2/
 $ make droidcam-cli
 $ make droidcam
 $ sudo ./install-client
 $ sudo ./install-video

```
