### ISSUE TITLE
Display battery life in DroidCam Linux client

### ISSUE THREAD

**Issue by robstewart57** [dev47apps/droidcam#167]
**Describe the feature you'd like to see added to the app**

**Feature request:** *Display battery life in the Linux client*

I use DroidCamX daily, connecting to the Linux client with WiFi. When I have long calls, I become anxious that my phone's battery is close to dying. If the Linux client GUI showed my the battery percentage, I could decide when to switch off my DroidCamX webcam before the battery dies.

Would it be possible to add information in the Linux client information about the phone's battery life?

Thanks.

**Comment by aramg** [comment]
Added in https://github.com/dev47apps/droidcam/releases/tag/v1.8.0

**Comment by niksingh710** [comment]
it is too nice too have that but is it possible to have that in the system tray some how ?
