### ISSUE TITLE
Droidcam not working on MS Teams (linux version)

### ISSUE THREAD

**Issue by ramonrrp** [dev47apps/droidcam#169]
**Description**
* Trying to use the app (with droidcamX) in desktop version of Microsoft teams for linux, but with no success;
* Droidcam is listed as a video option, but when selected in a reunion, the video preview gets black and the message "The video is not working. Not possible to use webcam for the video" is shown.

* Teams is working with my notebook  webcam

**Setup:**
Smartphone Xiaomi Mi A3 with Android one
Linux 5.8.0-53-generic
ubuntu 20.04 LTS
MS Teams desktop version build teams_1.4.00.7556

**Expected behavior**
I would be able to use Reunion options from MS Teams selecting Droidcam as video source as well

**Additional context**
All other stream options i've tryed are working, such as OBS, google meet, skype, and **including MS Teams in web browser version**

**Comment by aramg** [comment]
I believe MS Teams (Linux) is limited to 720p, set the webcam to 1280x720 and it should work.

**Comment by ramonrrp** [comment]
> I believe MS Teams (Linux) is limited to 720p, set the webcam to 1280x720 and it should work.

You're right!

Web version works with full HD resolution, but desktop version accepts only 720p

**Comment by anthonysomerset** [comment]
I want to add this appears to be same issue with Skype for Linux as well - it might be beneficial to drop this in as a note in the Readme
