### ISSUE TITLE
droidcam uninstaller does not remove all of its files

### ISSUE THREAD

**Issue by swestlake** [dev47apps/droidcam#171]
/opt/droidcam-uninstall does not remove,
/usr/share/applications/droidcam.desktop
it should also remove its own install script from opt.

**Comment by aramg** [comment]
Yes, it does? https://github.com/dev47apps/droidcam/blob/master/uninstall#L12

**Comment by swestlake** [comment]
the uninstall file you reference from the blob-master is not the same copy as /opt/droidcam-uninstaller.

/opt/droidcam-uninstaller does not contain the remove statement for the droidcam.desktop file.

It would also imho make sense, that it does not leave behind traces of itself when one runs /opt/droidcam-uninstaller.

"Yes, it does? https://github.com/dev47apps/droidcam/blob/master/uninstall#L12"

that is the file from the zip/tar extract -- and not /opt/droidcam-uninstaller which contains different contents.

You might want to review this bugreport a little more slowly, and try to keep track of just one uninstaller script, instead of multiple of them.

Perhaps merge the installs and  uninstall scripts, so that there is just "one install" and "one uninstall".

Otherwise users would be referencing install/uninstall scripts that get placed everywhere.

keep it a little more simple.

(and make sure you close the bugreport after you read the bugreport more carefully next time)

thanks.
