### ISSUE TITLE
missing log for uninstaller

### ISSUE THREAD

**Issue by swestlake** [dev47apps/droidcam#172]
I am testing droidcam install scripts for my own possible usage of this software -- maintaining updates these scripts would be used, and noticed an issue -- sometimes there's too many things on screen, and a log for either installing(or uninstalling) as well as upgrading could be helpful for the user to track of where changes are occuring during installation.

a written file called /var/log/droidcam/droidcam-inst.log can be helpful for the user to track later what was done during executing /opt/droidcam-uninstaller, installer, or when running an upgrade path for droidcam.

some further examples could potentially be paths like,
for installations:
/var/log/droidcam/droidcam-inst.log

upgrade paths:
/var/log/droidcam/droidcam-inst.log -- same

uninstall path:  -- if a user is troubleshooting and wants to start from scratch
/var/log/droidcam/droidcam-uninst.log

**Comment by aramg** [comment]
vast majority of users dont care or need this. You are welcome to modify or run the the scripts differently for your use-case.
