### ISSUE TITLE
Audio Device not detected

### ISSUE THREAD

**Issue by ajinzrathod** [dev47apps/droidcam#174]
I am using Ubuntu 20 and I have installed Droidcam. `sudo ./install-sound` did not produce any errors. But applications such as OBS and Zoom are not able to detect Audio Input source.

And closing the application also did not produce any error. 

But after I tried adding `pacmd load-module module-alsa-source device=hw:Loopback,1,0` (after and before Droidcam started); as shown [here](https://www.dev47apps.com/droidcam/linux/)

It shows the following error while closing the app.

```
(droidcam:107371): GLib-GObject-WARNING **: 21:22:30.458: invalid unclassed pointer in cast to 'GtkWidget'

(droidcam:107371): Gtk-CRITICAL **: 21:22:30.458: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(droidcam:107371): GLib-GObject-WARNING **: 21:22:30.458: invalid unclassed pointer in cast to 'GtkWidget'

(droidcam:107371): Gtk-CRITICAL **: 21:22:30.458: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(droidcam:107371): GLib-GObject-WARNING **: 21:22:30.458: invalid unclassed pointer in cast to 'GtkWidget'

(droidcam:107371): Gtk-CRITICAL **: 21:22:30.458: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

```

**Comment by ezxpro** [comment]
These GTK errors are normal if you launch the application from terminal, they have nothing to do with the issue you're pointing out

That being said, I'm having the exact same issue. I installed droidcam on Ubuntu 20.04 according to their instructions, I installed the sound device, no erros were shown, yet I have no sound.

**Comment by ezxpro** [comment]
I managed to solve this issue today. You probably followed the instructions in the official website (https://www.dev47apps.com/droidcam/linux/) to install it.

Very well, you SHOULD NOT install the audio loopback device  (command `sudo ./install-sound` in the guide above). At first I did it and that's what made the sound break. The worst of all is that no uninstall script is provided and even removing the installed modules using modprobe didn't solve it.

**Comment by aramg** [comment]
> **1. DON'T RUN install-sound SCRIPT**
> Through a Ubuntu 20.04 user post on another network, I learned that you SHOULD NOT install the audio loopback device (command `sudo ./install-sound` in the guide above).
> 
> I experienced it myself: if you run that script the sound won't work and removing the installed module (with `modprobe -r`) and related config files doesn't solve it. I had a partition backup and restored it to solve the issue, but otherwise I think you either have to know what went wrong or reinstall the OS ( you may try the second answer on[ this closed issue too](https://github.com/dev47apps/droidcam/issues/60). I didn't try that though).
> 
> Another issue is that removing this module broke other systemd stuff here, not a good idea

Can you elaborate, the script adds `/etc/modprobe.d/` and a `/etc/modules-load.d/` entries for snd-aloop.
How does that lead to having to re-install the OS ?

>Now you're connected, but have no sound. To get the sound you must have the video already connected, then just run $ >pacmd load-module module-alsa-source device=hw:Loopback,1,0 and you're done. Sound will work until the next reboot, > whether on Wi-Fi or USB.

The client wont connect audio if snd-aloop is not loaded, you must have another config entry that loaded it, or?

**Comment by aramg** [comment]
@ajinzrathod sound on Linux is very finicky, droidcam will make the audio available though the Loopback device. Getting that into 3rd party programs depends on your distro and the programs themselves.

If you can access audio with `arecord` or vlc using the `hw:X,Y,Z` label the client prints, then the client is working.

**Comment by ezxpro** [comment]
@aramg what I was saying is that I couldn't get the sound working on Ubuntu 20.04. then osaw a post in askubuntu, if I'm not mistaken, where a user with the same distro mentioned that for him the sound worked normally without installing the loopback device, but he then ran that script and the audio stopped working. 

I thought that might be the reason my audio didn't work, do I liked into that script to see what it did and I removed the snd-aloop device using modprobe. After doing that droidcam stated to complain that the usbmuxd service was not running, i verified that indeed it was not starting even after a reboot and I couldn't fix that, so that's why I had to restore a backup from the whole os.

The point is, after 8brestoeed the os, I skipped the loopback thing and audio worked normally.

I tried just tried that on another machine but it did not work though. I had to install the loopback device for it to work o. The second machine 


Bit either way,I regret buying this app, it's so riddled with bugs on Linux, the developers should state the Linux version is experimental. Sound sometimes randomly doesn't activate and there's no way to rotate the camera 90 degrees, only 180 degrees. I tried 3 smartphones,on all 9f them the image is rotated by default.

This is unusable on Linux

**Comment by ajinzrathod** [comment]
@ezxpro 
> Now you're connected, but have no sound. To get the sound you must have the video already connected, then just run $ pacmd load-module module-alsa-source device=hw:Loopback,1,0 and you're done. Sound will work until the next reboot, whether on Wi-Fi or USB.

And now my audio is working. Thanks bro :). But those warnings are still there.  

BTW, what is `device=hw:Loopback,1,0` and how to change it. I mean how do you know 1,0 should come. I have no idea what this is. Are there any docs or anything related to it.

**Comment by ezxpro** [comment]
> @ezxpro
> 
> > Now you're connected, but have no sound. To get the sound you must have the video already connected, then just run $ pacmd load-module module-alsa-source device=hw:Loopback,1,0 and you're done. Sound will work until the next reboot, whether on Wi-Fi or USB.
> 
> And now my audio is working. Thanks bro :). But those warnings are still there.
> 
> BTW, what is `device=hw:Loopback,1,0` and how to change it. I mean how do you know 1,0 should come. I have no idea what this is. Are there any docs or anything related to it.

Well,  the also documentation on Arch Linux talks a bit about it: https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#Virtual_sound_device_using_snd-aloop

Seems like it's a virtual sound device, but idk anything about this

**Comment by ajinzrathod** [comment]
My `GTK` error is yet not solved while audio issue is solved so closing this. May reopen if necessary
