### ISSUE TITLE
Config setting for the zoom level

### ISSUE THREAD

**Issue by hmlendea** [dev47apps/droidcam#177]
Hello,

I need to use zoom in order to get a proper image for my camera.

The problem is that the zoom setting is not saved and I have to do zoom in again each time I connect to the phone.

I also rely on the vertical flip setting, and that one is actually saved. I think the zoom level should also be saved.

**Comment by aramg** [comment]
Merging this with #151 .
Either the app needs to restore the zoom, or the client apply it on launch.
