### ISSUE TITLE
Device not found (/dev/video[0-9]). Did you install it?

### ISSUE THREAD

**Issue by OmarAbdelhafiz** [dev47apps/droidcam#178]
This is a known bug.
When connecting Video from an Android device to a Linux device (Ubuntu 20.04.2 LTS) through a USB cable, it gives the following error message and disconnects:
Device not found (/dev/video[0-9]). Did you install it?

I think I found a way to reproduce the bug.

1 Connect normally.
2 Restart the Ubuntu system while the Linux Droidcam client is still running.
3 Trying to connect after the restart yields this error.

Feel free to close this Issue if the problem was addressed elsewhere.
Thanks in Advance.

**Comment by aramg** [comment]
`Device not found ` means no video loopback devices were found. Having the client running and rebooting the system should not affect it

How do you fix it after, re-install?
What are the contents of `/etc/modules-load.d/droidcam.conf` and `/etc/modprobe.d/droidcam.conf`?

**Comment by OmarAbdelhafiz** [comment]
The bug is mentioned here already.
https://askubuntu.com/questions/1133007/droidcam-installation-error-on-ubuntu-18-04

yeah, a re-install solved it.

Current working condition:
/etc/modules-load.d/droidcam.conf
```
videodev
v4l2loopback_dc
```
--
/etc/modprobe.d/droidcam.conf
```
options v4l2loopback_dc width=640 height=480
```

**Comment by aramg** [comment]
hm, the files look fine, I am surprised the module doesn't load on boot.
When you see the error again, can use run `v4l2-ctl --list-devices` and also `lsmod | grep v4l` -- any output?
If you use `sudo modprobe v4l2loopback_dc` does it start working?

**Comment by juju2112** [comment]
I have this same problem. When I run `sudo ./install`, I get:

```
insmod: ERROR: could not insert module /lib/modules/5.4.0-74-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Bad address
```

I I modify the files to what is listed above, I still get `Device not found (/dev/video[0-9]). Did you install it?`

**Comment by aramg** [comment]
`sudo ./install` must be from an older version of the client, did you download the latest one from the website or the releases page here?

Usually insmod errors are because of kernel updates, the v4l2loopback needs to be rebuilt for your current kernel.
`sudo ./install-video` in the newest client.

**Comment by juju2112** [comment]
@aramg I see. It looks like I downloaded an old version. That error is gone, but now it's not recognizing my device. I'm assuming that is a different issue, though, so I will experiment with it.

Thanks.

**Comment by juju2112** [comment]
Ah, I fixed my other issue, too! Even though I had enabled debug mode on my Android phone, I still had to go into Developer Settings and enable Debug over USB.

Thanks for the help.
