### ISSUE TITLE
cli version cannot be stopped once connection fails

### ISSUE THREAD

**Issue by meutzitzu** [dev47apps/droidcam#180]
**Describe the bug**
unable to quit `droidcam-cli` after connection is dropped (`Ctrl`+`C` does NOTHING)

**Expected behavior**
You should be able to reset the connection from the terminal, by stopping the program, even ignoring this, it's undesirable to have to close your terminal tab in order to stop the program

**Additional context**
`droidcam-cli`, Linux version
connection can be dropped for whatever reason, be it the USB cable disconnedting, be it the network gods not getting enough fresh sacrifices, it ultimatley does not matter, what matters is, whenever you press `Ctrl`+`C` the program should stop.

**Comment by aramg** [comment]
Must be a blocked network syscall.
Until this is fixed, you can use Ctrl+Z to background the app, `jobs` then then `kill -6 %N`

**Comment by aramg** [comment]
Hopefully fixed with https://github.com/dev47apps/droidcam/releases/tag/v1.8.0
