### ISSUE TITLE
Installation with Fedora 34 and secure boot is not working

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [dev47apps/droidcam#181]
**Describe the bug**
I tried to install droidcam on Fedora 34 with enabled secure boot. I get a lot of errors. First I get the following error when trying the install-video script:

![Bildschirmfoto von 2021-06-24 23-03-09](https://user-images.githubusercontent.com/41188546/123332115-64c22380-d540-11eb-9464-b6d35fb2f748.png)

After removing the modprobe line, it got a little further:

![Bildschirmfoto von 2021-06-24 22-59-26](https://user-images.githubusercontent.com/41188546/123331913-2af11d00-d540-11eb-9743-f2bb0281971f.png)

After that I tried to run the install-dkms script which actually installed the v4l2loopback_dc module with dkms. But after trying to load the module, it failed. Dmesg has the following output:

![Bildschirmfoto von 2021-06-24 23-05-26](https://user-images.githubusercontent.com/41188546/123332365-b2d72700-d540-11eb-8637-972ffec239d2.png)

**Expected behaviour**

Droidcam should install all video drivers correctly and should load them when using the install-video or install-dkms script.

**Comment by aramg** [comment]
It looks like the entire V4l2 sub-system might be missing. Is this a custom compiled kernel, or ?
Does `modprobe videodev` work?
Can you install regular v4l2loopback module?

**Comment by Sebastian-Hirsch** [comment]
I use the stock fedora kernel. The fedora kernel does not seem to have the v4l2loopback driver (have read something about that but I haven't a link). Modprobing the videodev kernel driver does not generate any output. Is there a way to test this?

**Comment by aramg** [comment]
`lsmod | grep videodev` should find it, if loaded

**Comment by Sebastian-Hirsch** [comment]
Seems like it loaded.

![Bildschirmfoto von 2021-06-25 18-46-15](https://user-images.githubusercontent.com/41188546/123458707-a3f68000-d5e5-11eb-9597-f3e11d8d577b.png)

**Comment by aramg** [comment]
hmm, in your 2nd screenshot I also see 'failed to load symbols from ... videodev.ko.xz: Invalid argument' from `depmod -a`.

Now that videodev is seemingly loaded, what's the result of `modprobe v4l2loopback_dc` ?

**Comment by Sebastian-Hirsch** [comment]
I had droidcam removed and reinstalled it completely. I have errors inm the installation and when trying to modprobe the driver.

![Bildschirmfoto von 2021-06-25 18-52-42](https://user-images.githubusercontent.com/41188546/123459501-a4434b00-d5e6-11eb-8760-2ae38ab330d3.png)

**Comment by Sebastian-Hirsch** [comment]
dmesg shows this:
![Bildschirmfoto von 2021-06-25 19-03-12](https://user-images.githubusercontent.com/41188546/123460512-0781ad00-d5e8-11eb-9ce1-20f56afe4df8.png)

**Comment by aramg** [comment]
These errors usually come from having multiple kernel versions clashing.
You have 5.12.11-300 and 5.12.12 both present, the module is being compiled for one but installed into the other.
I'm not sure what the exact fix is, the make scripts use `uname -r` to get the kernel version, maybe you get different outputs when with/without sudo ?

**Comment by Sebastian-Hirsch** [comment]
uname -r always gives the same output.
![Bildschirmfoto von 2021-06-25 19-06-48](https://user-images.githubusercontent.com/41188546/123460823-8971d600-d5e8-11eb-9f85-b9e10b333793.png)
And I only use the scripts provided by droidcam.

**Comment by aramg** [comment]
OK, one more though, whats `echo $KERNELRELEASE`
Try `export KERNELRELEASE=$(uname -r)` then ./install-video

**Comment by Sebastian-Hirsch** [comment]
echo $KERNELRELEASE is an empty line.

**Comment by Sebastian-Hirsch** [comment]
I will reboot and see if it still works.

**Comment by Sebastian-Hirsch** [comment]
Okay, everything seems to work now, awesome! Thank you for your help!
