### ISSUE TITLE
ALSA Loopback sound card hijacks default audio output.

### ISSUE THREAD

**Issue by junglized** [dev47apps/droidcam#185]
**Describe the bug**
After installing sound with `sudo ./install-sound` ALSA Loopback sound card appoints itself as default output device taking over line-out.

**Expected behavior**
I'd like Line-out to keep being set as default after inslalling DroidCam sound.

**Additional context**
Loopback sound seems to be pretty persistent and stubborn. I tried to edit `/etc/pulse/default.pa`, delete `~/.config/pulse` and those didn't work. There is that file called `b6ec9c24cb12dd0a71eec661605f051a-default-sink` in `~/.config/pulse` which seems to resurrect itself after being deleted and system rebooted. It contains entry for loopback card, but when it's contents is overwritten with line-out details, then saved and system restarted, it comes back to have loopback card written in.

The only thing which worked for me was executing `pactl set-default-sink 'alsa_output.pci-0000_00_1b.0.analog-stereo'` declared in startup applications. But I wish I didn't spend hours to figure that out.

BTW: my system is Pop!_OS 20.04.

**Comment by aramg** [comment]
The Loopback card is part of the Linux kernel. I'm not sure what droidcam can do differently other than figure out what the trick is to avoid the default device take-over. The `set-default-sink` command be added with `install-sound` as a potential workaround.

The install script adds a line to `/etc/modprobe.d/droidcam.conf` with `snd-aloop index=N` where N is the card number when the loopback device is initially loaded. What did the index end up as on your system?

**Comment by aramg** [comment]
And are there are there any other snd-aloop instances, `grep -r "snd-aloop" /etc/modules-load.d /etc/modprobe.d` ?

**Comment by junglized** [comment]
@aramg

"What did the index end up as on your system?" - 2,

"And are there are there any other snd-aloop instances" - I have those two lines displayed in terminal after executing command you provided:

```
/etc/modules-load.d/droidcam.conf:snd-aloop
/etc/modprobe.d/droidcam.conf:options snd-aloop index=2
```

**Comment by aramg** [comment]
Then it seems this is a PulseAudio issue. This answer implies what you did with `pactl set-default-sink` is the accepted way: https://askubuntu.com/a/14083. 

But I am not sure what the DroidCam installer can do here, since it would have to guess which sink to set as the default. I'll add a comment to the client download page, so that at least others don't have to search around as much.

**Comment by junglized** [comment]
Fair enough then, thank you for your time.

Best regards!.
