### ISSUE TITLE
DroidCam with the v4l2loopback and build rpm-packages

### ISSUE THREAD

**Issue by AKotov-dev** [dev47apps/droidcam#188]
Hello, **aramg**. Thank you very much for your work and droidcam. Today I build rpm-packages for my Mageia Linux-8 already from a new one droidcam-v1.8.0 and I have successfully started broadcasting video and audio over Wi-Fi! This festive day will go down in history! :)

I apologize in advance for my bad English, I communicate through an online translator. :)

I don't have any error messages. But since I have little experience with cameras/video/audio, if you don't mind, please give me some advice...

I just want to clarify that I used the usual dkms-v4l2loopback (0.12.5), which already exists in the repositories Mageia Linux-9. 
Here are my rpm packages, as a confirmation: https://github.com/AKotov-dev/droidcam-rpm/tree/main/archive

The logic of launching droidcam is as follows...

Autoloadable modules and configuration
--
/etc/modprobe.d/droidcam.conf
```
options v4l2loopback card_label="DroidCam" exclusive_caps=1
options snd-aloop index=2
```
/etc/modules-load.d/droidcam-mod.conf
```
videodev
v4l2loopback
snd-aloop
```
Droidcam startup script with microphone and camera setup/activation
---
/usr/bin/droidcam.sh
```
#!/bin/bash

### DroidCam start with droidcam_audio script

#Kill if running (Only one instance. For more there is a droidcam-cli)
[[ $(pidof droidcam) ]] && killall droidcam
[[ $(pidof v4l2loopback-ctl) ]] && killall v4l2loopback-ctl

#Assigning the camera format and size. If this is not done, droidcam will not understand what kind of camera was slipped to it.
v4l2loopback-ctl set-caps "video/x-raw, format=I420, width=640, height=480" \
$(v4l2-ctl --list-devices | sed -n "/Droid/,// p" | head -n +2 | grep "video") &

droidcam &

sleep 5

# Mic Up (droidcam_audio)
[[ $(pactl list | grep droidcam_audio) ]] || pacmd load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio

#Set droidcam_audio as Default Mic
pacmd set-default-source 'alsa_input.hw_Loopback_1_0'

exit 0;
```
**Is there anything that can be improved/changed here? For example:**
1. Is it possible `v4l2loopback-ctl set-caps "video/x-raw...` replace with any combination at the level `/etc/modprobe.d/droidcam.conf`?
2. Initially, I built droidcam with the module v4l2loopback_dc ( https://github.com/AKotov-dev/droidcam-rpm ). Which of the modules do you personally recommend using: v4l2loopback or v4l2loopback_dc?
3. Why exactly `sleep 5` (taken from other posts in the topic droidcam)? What exactly should I attach to (signal/event/pid), to do without `sleep 5`, and so that the smartphone's microphone is guaranteed to be connected and sound is coming from it?

It all works now, but I want to do it more carefully. :)

Thank you in advance, sincerely,
Alex

**Comment by aramg** [comment]
Hi Alex, I am not sure what the purpose of this issue is, but here's some answers.

* Packaging this app isn't trivial, which combined with the fragmentation in Linux (DEB, RPM, pacman, flatpak, snap, nixpkgs, etc.) makes is hard to maintain.

* I am generally against people trying to re-package and re-distribute the client. If that is your intent, I would rather you not do it. If you are just packaging for yourself, that's OK. If you want to craete some PRs that improve the installation / running of the client, thats OK.

1. I don't think its possible to set image format and specific size for v4l2loopback via /etc/modprobe.d. This is the main difference with v4l2loopback-dc.
The droidcam client will set the image size, so I am not sure why you have `v4l2loopback-ctl` in there to begin with. See "v4l2loopback usage examples" https://github.com/dev47apps/droidcam/blob/master/README.md#v4l2-loopback-webcam-driver
2.  No recommendations, it depends on your goals. v4l2loopback is sometimes easier to install but requires more manual configuration.
3. There are unfortunately no signals that can be watched for audio connection. In #106 we watch the output of the client to grab the audio device and load it. In order to guarantee audio is running, the client would need to generate signal or run `pacmd` itself.

**Comment by AKotov-dev** [comment]
Hi, **aramg**.
Thank you so much for your answers. I realized that you leave the use of a particular kernel module to the discretion of the user, is also clear with the sound (thanks for the links).

Your quote:
```
I am generally against people trying to re-package and re-distribute the client.
If that is your intent, I would rather you not do it. ...
```
droidcam/droidcam-cli is a wonderful tandem that is distributed under the GPL-2.0. Changing the source code during the build process is a normal, regular procedure. For example, starting with the droidcam-1.7.3 You have added an "app-indicator". There is no such package in Mageia Linux, but there is "ayatana-appindicator". For this reason, the source code was changed:
```
sed -i 's/appindicator3-0.1/ayatana-appindicator3-0.1/' %{_builddir}/%{name}-%{version}/Makefile
sed -i 's/<libappindicator/<libayatana-appindicator/' %{_builddir}/%{name}-%{version}/src/droidcam.c
```
In addition, you added libjpeg-turbo 2.1.0 to the build, which allowed me to find a package from Mageia (lib64jpeg-devel-2.0.5-1), in the past, there were problems broadcasting video from the camera when connected via WiFi. It turns out that this bug has already been described and fixed here: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.6 (Corrupt JPEG data: premature end of data segment). Now I have made a request to update this package to Mageia support and am waiting for them to raise the version if possible libjpeg-turbo.

There were no other changes to the source code, only the GUI. I build packages for my distribution, which is a derivative of Mageia Linux (rather, it is not even a derivative, but a manufacturing technology.), so it's almost for personal use. I will say more, I have no desire and experience to explore and change the droidcam-cli code. This is your personal invention and it is customary to respect it in Linux. I'm not a big expert on licensing, but if you still have any worries about saves the authorship of your source code, you can always raise the license to GPLv3, which will force the source code modifier to indicate the canonical, that is, your personal authorship. This will put the code modifier in an extremely uncomfortable position in case of problems during distribution, and you can always prove that the final code is not original. But I say this so, by the way. I just feel that you are worried about something.

I would like to thank you once again for your very useful and necessary work. I wish you success in the development of your project!

Sincerely,
Alex

**Comment by aramg** [comment]
Hi Alex, I dont mind if you change & improve the code and even consider opening pull requests here. The GPL license is intentional, you can change the code as much as you want. 

`I build packages for my distribution` <- this is what I prefer people not do.  Eventually if your package becomes outdated with the phone apps and stops working, it will result in negative user experience. This has happened before. It's also not trivial to automate the video and audio driver installation. IMO there is too many distros and derivatives, and I prefer to distribute the client pre-packaged here on GitHub and on the website.

Are there any problems with the existing releases packages with your Mageia Linux derivative??

**Comment by aramg** [comment]
@AKotov-dev I also noticed you have copies of DroidCamX on your GitHub. This is against the app terms & conditions. Can you explain that to me?

**Comment by AKotov-dev** [comment]
Hello, **aramg**.
Considering all the pros and cons, I decided to focus on using your `v4l2loopback_dc` module, since you support it and there is less red tape with it. Probably later, I will add the ability to change the resolution of the `Droidcam` camera to my package. Maybe this will also interest someone... :)

In order not to take into account the architecture, there is one script running here with the participation of **zenity** (you need to install the package if it is missing). It changes the settings (`width=, height=`) of loading the configuration of the module `v4l2loopback_dc` `/etc/modprobe.d/droidcam.conf`. To do this, you will need to overload this module, and for this you need root privileges. The script uses `pkexec` for this and recursively restarts itself after entering the correct password. Since `zenity` is practically a GUI, the script is run from a shortcut:  

/usr/application/droidcam-resolution.desktop
```
[Desktop Entry]
Name=DroidCam-Resolution
Name[ru]=DroidCam-Resolution
Comment=Change DroidCam resolution
Comment[ru]=Изменение разрешения Web-камеры
Exec=droidcam-resolution.sh
Icon=/usr/share/icons/droidcam.png
Terminal=false
Type=Application
Categories=Video;AudioVideo;
```
/usr/bin/droidcam-resolution.sh
```
#!/bin/bash

# Select DroidCam resolution script
# Requires root privileges (pkexec) and zenity

if [ "$EUID" != "0" ] ; then pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY "$0"; exit; fi;

a=$(zenity --list --radiolist --title="Droidcam resolution (v4l2loopback_dc)" --width=350 --height=250 \
--column="#" --column="Width" --column="Height" 640 640 "480" 960 960 "720" 1280 1280 "720" 1920 1920 "1080")

case $a in
    640)
       w=640; h=480
      ;;
    960)
       w=960; h=720
      ;;
   1280)
       w=1280; h=720
      ;;
   1920)
       w=1920; h=1080
      ;;
    *)
       exit 0
      ;;
esac

sed -i "s/width=*[0-9]*/width=$w/g" /etc/modprobe.d/droidcam.conf
sed -i "s/height=*[0-9]*/height=$h/g" /etc/modprobe.d/droidcam.conf

# Kill droidcam if running & v4l2loopback_dc is busy
[[ $(pidof droidcam) ]] && killall droidcam
rmmod -f v4l2loopback_dc && modprobe v4l2loopback_dc

zenity --info --no-wrap --text="Droidcam resolution: "$w"x"$h""

exit 0;
```
Result: the camera resolution has been changed, the v4l2loopback_dc module has been reloaded:
```
> cat /etc/modprobe.d/droidcam.conf
options v4l2loopback_dc width=1280 height=720
options snd-aloop index=2
```
You can quickly view the new parameters of the `Droidcam` camera in  program `Cheese`.

Sincerely,
Alex
