### ISSUE TITLE
Auto loading sound driver on client startup?

### ISSUE THREAD

**Issue by Ninjastorm380** [dev47apps/droidcam#190]
I have been using your awesome app now for quite a bit, and I love almost every bit of it! (thanks for making btw)

My only quip with the Linux client so far is having to enter a terminal command to get sound working every time I launch it. Given what info I have from the UI, how the command that is used is formatted, and a little clever insight from scripting, I figure it should be possible to form and run said command with string concatentation and the variable that holds the pulseaudio sound device info from within the code itself.

Is this possible to do?

**Comment by aramg** [comment]
@Ninjastorm380 not all distros use PulseAudio (I assume you are referring to PulseAudio commands), and for the ones that do: PA seems to behave differently across them. There isn't a command the client could run that would just work on all Linux systems.
This is arguably Linux's biggest flaw, the fragmentation which has gotten only worse over the years.

Having said that, you should be able to easily script launching the client and running the necessary command(s); or build you own version of the client that runs the command(s) automatically.

**Comment by Ninjastorm380** [comment]
Thank you for answering! Indeed, I have a little script now that I launch droidcam with from my desktop, instead of using the usual desktop file / launcher entry. Perhaps someday said fragmentation will eventually cease to exist.
