### ISSUE TITLE
Error when changing camera resolution.

### ISSUE THREAD

**Issue by GaboTheCoder** [dev47apps/droidcam#191]
**Describe the bug**
/lib/modules/5.10.56-1-MANJARO/kernel/drivers/media/video/v4l2loopback-dc.ko is non existent.

**Expected behavior**
Be able to change camera resolution when running
``sudo insmod /lib/modules/ `uname -r`/kernel/drivers/media/video/v4l2loopback-dc.ko width=1920 height=1080``

**Additional context**
OS: Manjaro Linux 5.10.56-1
Arch: x64

**Comment by AKotov-dev** [comment]
> /lib/modules/5.10.56-1-MANJARO/kernel/drivers/media/video/v4l2loopback-dc.ko is non existent.

Hi, **GaboTheCoder**.
+ DroidCam + droidcam-cli v1.8.0 (in the section Arch Linux): https://pkgs.org/search/?q=droidcam
+ And here is the kernel module that you are looking for: https://pkgs.org/search/?q=v4l2loopback-dc-dkms

Is this by any chance what you are looking for?

By the way, **GaboTheCoder**, if the camera resolution you are trying to set (width=1920 height=1080) works fine, could you please let us know? The fact is that in his question https://github.com/dev47apps/droidcam/issues/188 I have not been able to verify this and I have to rely only on luck. :)

Sincerely,
Alex

**Comment by aramg** [comment]
@GaboTheCoder this is not a bug. You can email support@dev47apps.com for support.
Make sure to follow the instructions on the website at https://www.dev47apps.com/droidcam/linux/.
The pkgs.org links above are UNOFFICIAL and you are welcome to get support for those from the Manjaro community.
