### ISSUE TITLE
No support for 1920x1080@60fps with OBS

### ISSUE THREAD

**Issue by redcloud80** [dev47apps/droidcam#193]
Is it possible to add support to 1920x1080@60fps with OBS? I see 30fps only is available in OBS custom configuration. Tried with USB connection but nothing changes against WiFi connection. I'm using Windows 10. Thanks!

**Comment by aramg** [comment]
The droidcam client is limited to 30fps, you can use [DroidCam OBS](https://www.dev47apps.com/obs) to get 60fps video into OBS Studio.

Also, (a) this is not a support form and (b) this is the for the Linux client. Support/help emails are on the app store.
