### ISSUE TITLE
Audio device missing despite there being one on the mobile (Linux)

### ISSUE THREAD

**Issue by SarangT123** [dev47apps/droidcam#194]
**Audio device missing despite there being one on the mobile (Linux)**

**Expected behavior**
Was supposed to connect without any issues 

**Additional context**

![Screenshot](https://user-images.githubusercontent.com/72746858/132936802-71c6da8f-4e03-4c00-be61-5787bea5703c.png)

**Comment by aramg** [comment]
You need to have the ALSA loopback device loaded on the Linux system.
