### ISSUE TITLE
deprecated gtk_menu_popup

### ISSUE THREAD

**Issue by ohquait** [dev47apps/droidcam#197]
+ libtoolize -c -f
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
+ make -O -j16 droidcam
gcc  -Wall -O2 src/droidcam.c src/resources.c src/connection.c src/settings.c src/decoder.c src/decoder_snd.c src/decoder_v4l2.c src/av.c src/usb.c src/queue.c -o droidcam  `pkg-config --libs --cflags gtk+-3.0` `pkg-config --libs x11` `pkg-config --cflags --libs appindicator3-0.1` -I/opt/libjpeg-turbo/include /opt/libjpeg-turbo/lib`getconf LONG_BIT`/libturbojpeg.a `pkg-config --libs --cflags libswscale libavutil` -lspeex -lasound -lpthread -lm -lusbmuxd
src/droidcam.c: In function ‘the_callback’:
src/droidcam.c:276:25: warning: ‘gtk_menu_popup’ is deprecated: Use '(gtk_menu_popup_at_widget, gtk_menu_popup_at_pointer, gtk_menu_popup_at_rect)' instead [-Wdeprecated-declarations]

**Comment by aramg** [comment]
Did the build fail, or just the warning?

There is a comment in the code (src/droidcam.c:276) about this

**Comment by jonasbove** [comment]
I'm trying to use DroidCam on Manjaro Gnome and had the same warning.
The build didn't fail, but the application doesn't work as is.

**Comment by aramg** [comment]
@jonasbove do the binaries from the website work OK?

**Comment by ohquait** [comment]
Excuse me, I can't understand it anymore
had an accident at work in November,
What I can definitely say is that the current release works great with Webcamoid and others on PCLinuxOS for me.

**Comment by walderf** [comment]
to "fix" this issue you can add -Wno-deprecated-declarations to CFLAGS

`CFLAGS = -Wall -O2 -Wno-deprecated-declarations`

**Comment by aramg** [comment]
This is should be gone in the latest releases. Commit 71a74d22 replaced gtk_menu_popup with gtk_menu_popup_at_pointer
