### ISSUE TITLE
DroidcamX Android app forgets picture settings at every connect

### ISSUE THREAD

**Issue by sleeksorrow** [dev47apps/droidcam#201]
**Describe the bug**
Everytime I connect to the Android DroidcamX app, many of the settings are resetted and I need to take the phone out of the holder e.g. to activate autofocus again. Also the last zoom level is resetted. Maybe other settings, too, that I don't use. Other settings like which camera I chose is remembered throughout app restarts.

This happens not only if the app is closed and restarted but also if it's still running in the background and I just stop and connect again from the client app.

**Expected behavior**
f I just reconnect to the still running app I expect to get the exact same picture as I had before the reconnect. Additionally it would be great if it's even after exiting and restarting the app.

**Comment by aramg** [comment]
Yes (known bug/feature request).
See #151

**Comment by sleeksorrow** [comment]
Sorry I missed that one. Thanks!
