### ISSUE TITLE
Select the input device for DroidCam

### ISSUE THREAD

**Issue by DJ-Panncake** [dev47apps/droidcam#204]
Hi there,

If I connect multiple devices with my linux-laptop (tablet for screen sharing with `scrcpy` via the terminal, smartphone for camera access with droidcam via the app) i can't run droidcam `error adding adb forward`. Is there a way i can tell droidcam which of the connected devices it should use to connect to?

**Comment by aramg** [comment]
See the ANDROID_SERIAL comment at https://www.dev47apps.com/droidcam/linux/ (Install -> Extra Notes -> Android).
And please use support@dev47apps.com for general help.
