### ISSUE TITLE
Uninstall script fails to remove /opt/droidcam folder

### ISSUE THREAD

**Issue by haddady** [dev47apps/droidcam#207]
**Describe the bug**
uninstall script fails to remove /opt/droidcam folder

**Expected behavior**
all files clean up including folder /opt/droidcam and it's content.

**Additional context**
script doesn't  remove /opt/droidcam folder , option -r needs to be added to rm to fix that  " rm -rf /opt/droidcam "

**Comment by slinkthedev** [comment]
#239 fixed it in this pull request

**Comment by aramg** [comment]
Thanks!
