### ISSUE TITLE
Exposure lock not working

### ISSUE THREAD

**Issue by Man-with-Arrow** [dev47apps/droidcam#208]
**Describe the bug**
Exposure lock doesn't work. Either through the desktop UI, or through the app; pressing the button has no effect, exposure changes when I move.

**Expected behavior**
After pressing the "exposure lock" button, exposure should be locked to current value,

**Additional context**
Using Galaxy S2 on Android 11, and Fedora 34 on Desktop. Using v4l2loopback-dc.

**Comment by aramg** [comment]
Closing this as a support question (contact email on the appstore).
