### ISSUE TITLE
Do not force the user to click extra buttons when they ask droidcam to quit

### ISSUE THREAD

**Issue by pde** [dev47apps/droidcam#211]
Choosing the "quit" option from the droidcam applet menu (for instance, to deal with #210) causes droidcam to open a dialog asking `Are you sure? Connection will be lost`. Sometimes this even seems to open invisibly on some other desktop workspace. This is very bad behavior: the user asked to quit, and the app made them do more work.

A dialog asking "are you sure" is appropriate if quitting an app may cause data loss, but should be removed here because the stakes are not high. If the user accidentally cuts off video they were wanting to use, they can start droidcam again.

**Comment by aramg** [comment]
You can disable the exit confirm dialog via ~/.config/droidcam, set `confirm_close` to `0`.
