### ISSUE TITLE
Rotate view

### ISSUE THREAD

**Issue by safderali5** [dev47apps/droidcam#213]
Droidcam is missing essential setting to rotate video 90 degree clockwise and anticlockwise (even in paid version). The use case is when phone is in portrait mode, the video on the laptop is shown as landscape.
Having option to rotate video at source will solve the problem for all kind of applications using this virtual cam

**Comment by safderali5** [comment]
The rotate option is missing from Linux client, while it is present in windows client.

**Comment by aramg** [comment]
Hi, you can invert the video size to achieve 90º video -- see the HD Mode section at https://www.dev47apps.com/droidcam/linux/.

The client doesn't have native rotation due to a lack of easy-to-use graphics libraries on Linux.

**Comment by safderali5** [comment]
That trick disturbs the whole aspect ratio. Would be better if client has it native support or droidcam-cli have that support.

**Comment by safderali5** [comment]
I found a way to rotate it using ffmpeg
ffmpeg -i /dev/video10 -vf "rotate=90*PI/180" -f v4l2 /dev/video11

Is there anyway you can add that to droidcam code using ffmpeg api
