### ISSUE TITLE
Linux droidcam sees 640x480 as the highest resolution mode

### ISSUE THREAD

**Issue by pde** [dev47apps/droidcam#214]
I have an iPhone 8 running driodcam with a linux desktop. On the iPhone I have video quality set to "very high", and this device is nominally capable of 4K recording at 30 or 60 fps. On linux, I see only 640x480 video input though;

```
pde@laptop:~$ v4l2-ctl -D
Driver Info:
	Driver name      : Droidcam
	Card type        : Droidcam
	Bus info         : platform:v4l2loopback_dc-000
	Driver version   : 5.10.92
	Capabilities     : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
pde@laptop:~$ v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YU12' (Planar YUV 4:2:0)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
```

**Comment by aramg** [comment]
Check out "HD Mode" under the Linux instructions.
https://www.dev47apps.com/droidcam/linux/

**Comment by aramg** [comment]
And please stop spamming issues, unless you're certain you've found a bug, use the support email found in the app/app store.

**Comment by pde** [comment]
Thanks for the resolution!

I can stop sending you UX bug reports if you like and email a support address, but the last two were real bugs (which you've fixed!) and this one is definitely... a place where usability could be improved :)

If this is an architectural limitation in the v4l2 kernel modules, my suggestion would be to put a hint or hyperlink to your documentation somewhere in the UI. That way people won't see all the options there and think that this one is just mysteriously missing. There are definitely folks hitting this issue in the wild and [not being able to solve it](https://www.reddit.com/r/linuxquestions/comments/lfudga/droidcam_resolution_wont_change/).

Happy to send a PR for that if you like. And thanks again for your great software!
