### ISSUE TITLE
Droidcam gives me a 90 degree rotated camera and it also rotates the app to landscape

### ISSUE THREAD

**Issue by GeorgeFlorian** [dev47apps/droidcam#217]
**Describe the bug**
Droidcam gives me a 90 degree rotated camera and it also rotates the app to landscape.
There is a Rotate/Flip option that can be checked in the Windows App, but it doesn't' change anything.

**Expected behavior**
I've used this app last month and it kept the app in portrait and the camera in portrait.

I do not own DroidCamX because the free version used to work in portrait mode.

**Comment by aramg** [comment]
Both DroidCam and DroidCamX (and DroidCam OBS) all force landscape to support more efficient video transfer.

The video should be correct on the PC, you are welcome to send a screenshot to support@dev47apps.com if you need assistance on this.
