### ISSUE TITLE
Fails to connect with Android 4.0.4 devices

### ISSUE THREAD

**Issue by kunver400** [dev47apps/droidcam#220]
I am trying to connect to an old sony device( Android ICS)
running [DroidCam v5.0.2](https://www.dev47apps.com/droidcam/android-4/#)

Error: Connection reset, is app running?

droidcam 6.16 on my oneplus 6 works fine though.

**Comment by aramg** [comment]
Old linux client downloads for DroidCam v5.xx
dev47apps.com/files/50/droidcam-v4l2-x64.tar.gz (64-bit)
dev47apps.com/files/50/droidcam-v4l2-x86.tar.gz (32-bit)
