### ISSUE TITLE
Negative zoom values for wide angle

### ISSUE THREAD

**Issue by porkyoot** [dev47apps/droidcam#222]
First of all thanks for the wonderful app !
I was looking for a way to get wide angle capable software so I can use my phone's wide angle camera. I would suggest a negative zoom but depending on the implementation, it might be better to add specific camera lenses as camera in the list of choices (front and back camera)
Thanks for your consideration

**Comment by aramg** [comment]
Hi, thanks for the feature request. I would highly recommend checking out [DroidCam OBS](https://dev47apps.com/obs), the newer DroidCam app which integrates with OBS Studio, essentially turning OBS into the PC client. It supports a much wider set of features, including Wide-angle lenses where possible.

**Comment by aramg** [comment]
Can be merged with #221
