### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by syswis** [dev47apps/droidcam#225]
The app/camera lock it'self to landscape even if the system setting is to always display in portrait mode.
How do I stop it to go in landscape?

**Comment by imahbub** [comment]
> The app/camera lock it'self to landscape even if the system setting is to always display in portrait mode. How do I stop it to go in landscape?

Same issue

**Comment by aramg** [comment]
Hi, this is by design -- the app will force landscape to capture data from the camera without having to do any post-processing. This allows for big optimizations under the covers.

**Comment by BeholdersEye** [comment]
> *edit: You can rotate the image on the PC side, if you need to get portrait video.

HOW?

**Comment by aramg** [comment]
On Windows, you would use the "DroidCamX Pro controls" at the bottom of the pc client.

For Linux, there is a note at the end of "HD Mode" section on how to achieve rotation:
https://www.dev47apps.com/droidcam/linux/
