### ISSUE TITLE
Droidcam linux client fails on connecting with adb

### ISSUE THREAD

**Issue by niklas-e** [dev47apps/droidcam#226]
**Describe the bug**
I'm trying to connect to my Android phone (OnePlus 9 Pro) via USB by using Droidcam client on Linux Mint 20.3 after installing the client by following the instructions at <https://www.dev47apps.com/droidcam/linux/>. However I'm getting the following error:

![image](https://user-images.githubusercontent.com/8472329/171363769-7166cac7-2adf-42cd-beb0-d894122778be.png)

**Expected behavior**
Happily connect Droidcam to my phone via USB

**Additional context**
I debugged this a bit and tested with a dummy C-program. Here's the findings:

Testing adb via terminal:

```shell
~$ adb start-server
~$ adb devices
List of devices attached
6e8cfb3	device
```

Created a dummy C-program to test the code of droidcam client which results in the aforementioned error:

```C
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void main(void)
{
  char buf[256];
	FILE* pipe;
	int rc = system("adb start-server");
	if (WEXITSTATUS(rc) != 0){
		fprintf(stderr, "Error, couldn't start adb");
		exit(1);
	}

	pipe = popen("adb devices", "r");
	if (!pipe) {
		fprintf(stderr, "Error, couldn't list devices");
		exit(1);
	}

  while (!feof(pipe)) {
    if (fgets(buf, sizeof(buf), pipe) == NULL) break;
		fprintf(stdout, "Line: %s", buf);
  }

  pclose(pipe);
}
```
Running the program:

```shell
~$ gcc c-adb-debug-test.c -o adb-debug
~$ ./adb-debug
Line: List of devices attached
Line: 6e8cfb3	device
Line: 
```

**Comment by aramg** [comment]
I am sorry for late reply on this, were you able to figure it out eventually?
Launching droidcam from the command line would be the way to try and see whats going wrong.

**Comment by niklas-e** [comment]
@aramg unfortunately I did not get it to work back then and haven't been able to use it since then. 

Now I tried again and it does work. Unfortunately I don't have a clue what could have fixed the issue... but I'm happy it works now :grin:

**Comment by goodnewsj62** [comment]
@aramg i am having same issue...  adb start-server works and adb devices list the devices on my terminal but for some reason it i keep getting Error loading devices:check if adb is installed

**Comment by devashish2024** [comment]
Hey there guys, I got the solution (works for me!)

So I literally had downloaded platform tools zip from Google Android Studio website, but when you do `adb` in terminal, it actually doesn't recognizes (unless you go to the platform tools folder).

So literally doing this worked!:
```bash
$ sudo apt-get update # optional
$ sudo apt-get install -y adb
$ adb start-server
$ adb devices # check the devices
List of devices attached
10BD5S0TFR0021N	device
```

Let's goo!
