### ISSUE TITLE
there was an error playing video from the webcam

### ISSUE THREAD

**Issue by pnkjmndhl** [dev47apps/droidcam#230]
Hi, I am using droidcam on Linux kernel 5.15 and android. It does not work for wifi connection or using a USB.

The droidcam app successfully connects the audio and video.
The web version using the ip address works.

But, when using cheese or zoom or meet,
cheese: takes a while to load and after a while, displays error (see attached image)
zoom: dark screen
meet: dark screen
![cheese](https://user-images.githubusercontent.com/28738378/190258763-cfa7d708-2f13-421e-b2c1-afb315b894f3.png)
![droidcam_client](https://user-images.githubusercontent.com/28738378/190258766-028e125a-e3fb-4ff7-9b1e-88f67be7140a.png)
![terminal](https://user-images.githubusercontent.com/28738378/190259355-a26416af-e488-472c-813d-e8a8cdf71c26.png)

**Comment by aramg** [comment]
Going to close this as outdated. Please reopen if issue is still present.
Note that if you use the standard `v4l2loopback-dkms` package, you may need to exclusive_caps option enabled.
