### ISSUE TITLE
Bash: /usr/bin/droidcam-cli: cannot execute binary files: Exec format error

### ISSUE THREAD

**Issue by yuvrajbhaia** [dev47apps/droidcam#232]
Hey, we've been working on a **Raspberry pi 3B with ubuntu 22.04** os working on it (without the GUI)
We've been trying to install Droidcam on it for the past 3 days yet don't seem to find a solution to this error, we used the instructions given below step by step and compiled the source code as instructed.
https://github.com/dev47apps/droidcam/wiki/Raspberry-PI

Despite all these efforts we keep running into the same error again and again;
**Bash: /usr/bin/droidcam-cli: cannot execute binary files: Exec format error**

We have a competition in a week and this is an integral part of the challenge. I would really appreciate it if you could help us with this issue urgently.

thanking you in advance

**Comment by aramg** [comment]
Please don't spam, you've already commented in the other thread.
The error looks like the compilation either failed or something is wrong with the environment. Make sure you're not trying to run the copy of `droidcam-cli` off the website, which isn't compatible with ARM based systems
