### ISSUE TITLE
Audio and video connection stopped working

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [dev47apps/droidcam#241]
**Describe the bug**

Droidcam has completely stopped working for me. Unfortunately its been quite long since I last used it and I am not sure which change is responsible. Could be related to a kernel upgrade (currently on version 6.2.1), could also be related to the upgrade to Android 13 (currently running Lineage OS 20.0 build of 27-02-2023). When I click connect I get a pop-up saying "Connection reset! Is the app running?". I can see the camera on the phone starting up though. If I select audio only I do not get a pop-up, but nonetheless there is no audio being received (pipewire version 0.3.66, the loopback device is in the "pro audio" profile, usually this results in microphone audio via the device named "Built-in Audio Pro 1".). Connecting through usb or wifi makes no difference.

dmesg does not show any errors when connecting, nor does running droidcam from the command line reveil any failure messages.

**Expected behavior**

Audio and video is received, no error pops up

**Additional context**

This is a Gentoo Linux PC connecting with a Lineage OS 20.0 phone

**Comment by aramg** [comment]
Hi, This is not a bug, just a network issue. 
Check out the tips under the first section at https://www.dev47apps.com/droidcam/help/

If you have both 2.4Ghz and 5Ghz wifi, make sure the phone and the pc are on the same one.

It sounds like the connection succeeds but immediately gets cut off. It could also be a system issue with Lineage OS or some sort of a security feature. Try opening the URL the Droidcam app shows in a browser.

**Comment by aramg** [comment]
Hi,

The network related code in the app is fairly straightforward and has been working reliably for a very long time. There have been no other similar issues reported. 

Just to be clear: connecting using the PC client, it fails to stream video. Opening the URL in a browser, then video loads after a while? What if you try curl,
`curl http://phone-ip:4747/video > /dev/null`

Based on everything reported, I would lean on the non-native Android system being the issue.
The browser will keep retrying, so perhaps after many failures it manages to get a stable connection through.  
Could you also try again with a browser, but pull up the Developer Tools (right-click, then "Inspect" on the webpage) and look through the 'Network' tab.

**Comment by AndrewAmmerlaan** [comment]
> Just to be clear: connecting using the PC client, it fails to stream video. Opening the URL in a browser, then video loads after a while?

Yes. Perhaps I can best describe my issue with a video: https://user-images.githubusercontent.com/8460628/222186948-0cda27b7-5998-4628-9fcf-d5b757ac1a99.mp4

To me, it looks like the client sends a request to start video/audio. The app correctly receives this, and starts the camera. However, the app hangs while starting the camera (possibly related to the warnings/errors in dmesg), thus the desktop client does not receive the expected response on time and therefore thinks the app is dead and pops-up with this error.

> What if you try curl,

This appears to work, though the video feed on the phone is choppy:
```
andrew@andrew-gentoo-pc ~ % curl http://192.168.1.186:4747/video > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 1070k    0 1070k    0     0  39215      0 --:--:--  0:00:27 --:--:-- 38040^C
```

> Could you also try again with a browser, but pull up the Developer Tools (right-click, then "Inspect" on the webpage) and look through the 'Network' tab.

![image](https://user-images.githubusercontent.com/8460628/222188790-a5a533e4-603f-4130-aeff-053cbf3f08b3.png)

Looks fine to me, a bit slow but no 404s.

> Based on everything reported, I would lean on the non-native Android system being the issue.

This phone has been running Lineage OS since Android 11 and Droidcam always worked fine. The only thing that is really different about it now compared to when I last tried this, is the upgrade to Lineage OS 20 (i.e. Android 13). Honestly I doubt it is a issue specific to Lineage OS, it is not that different from vanilla Android. In fact, for this specific model Lineage OS is officially supported by the manufacturer.

**Comment by aramg** [comment]
hmm, with curl and the browser working, I am not sure what we could investigate since on a system level the client does the same thing. In you video you are using adb, is the Wifi option exhibiting the same behavior?

**Comment by AndrewAmmerlaan** [comment]
> hmm, with curl and the browser working, I am not sure what we could investigate since on a system level the client does the same thing. In your video you are using adb, is the Wifi option exhibiting the same behavior?

The wifi connection is exactly the same.

> Edit: In your video you have 127.0.0.1 as the Wifi IP, make to change this to 192.168.1.186 otherwise you're still going through the local adb proxy

Yes, I did that of course. I still get the same pop-up.


I found that if I increase the resolution in the browser the video feed gets increasingly choppy until it cuts out completely at the HD levels. I'll try later to decrease the resolution of the client to match the working setting in the browser, maybe that will somehow make it work.

**Comment by AndrewAmmerlaan** [comment]
> I found that if I increase the resolution in the browser the video feed gets increasingly choppy until it cuts out completely at the HD levels. I'll try later to decrease the resolution of the client to match the working setting in the browser, maybe that will somehow make it work.

Limiting the resolution to 640x480 does not help unfortunately. I also tried using `droidcam-cli` but got the same error.

**Comment by aramg** [comment]
So to summarize, 

* curl works (no issues)
* the browser approach works (mostly no issues - what does the network tab look like at the higher resolutions when the image cuts out? any particular error messages? )
* the client, both gui and cli, get a connection reset every time?

Let me see if we can look into the code and maybe build a debug version to experiment with. 
Everything works fine for me so far.

**Comment by AndrewAmmerlaan** [comment]
> So to summarize,
> 
>     * curl works (no issues)
> 
>     * the browser approach works (mostly no issues - what does the network tab look like at the higher resolutions when the image cuts out? any particular error messages? )
> 
>     * the client, both gui and cli, get a connection reset every time?

Yes that is correct. The browsers network tab at the highest resolution looks the same. Though for some reason this time I didn't see the same "choppiness" as I saw last time. The client still complains about a reset connection though.

![image](https://user-images.githubusercontent.com/8460628/223546202-e979cf69-b370-419b-80ad-226cc6ef27b7.png)

**Comment by aramg** [comment]
I've uploaded an early build with an extra output line when the "connection reset" message gets generated.
The output will be on the command line, if you have a minute to try it out lets check if there is anything meaningful there.

https://github.com/dev47apps/droidcam/releases/tag/v1.9.0-RC

So far there isn't anything obvious as to why the client would get a reset while the other programs work as expected :/

**Comment by AndrewAmmerlaan** [comment]
> I've uploaded an early build with an extra output line when the "connection reset" message gets generated.
> The output will be on the command line, if you have a minute to try it out lets check if there is anything meaningful there.

With this version I'm seeing a 'Resource temporarily unavailable':

```
andrew@andrew-gentoo-laptop ~ % droidcam
Audio loopback device not found.
Is snd_aloop loaded?
Video: /dev/video2
Audio:
* daemon not running; starting now at tcp:5037
* daemon started successfully
4747
recv error (11) 'Resource temporarily unavailable'
recv error (11) 'Resource temporarily unavailable'
```

**Comment by aramg** [comment]
OK, great. Seems the socket could be timing out. I've increased the recieve timeout and rebuilt the binaries. Could you try the RC2 zip at https://github.com/dev47apps/droidcam/releases/tag/v1.9.0-RC

**Comment by AndrewAmmerlaan** [comment]
> OK, great. Seems the socket could be timing out. I've increased the recieve timeout and rebuilt the binaries. Could you try the RC2 zip at https://github.com/dev47apps/droidcam/releases/tag/v1.9.0-RC

This has partially fixed the problem for me. With this version video works reliably, though audio still isn't received on the client side. The "audio connected" pop-up does show on the phone, and the "Pro-audio" loopback devices are present in pavucontrol as usual though the activity indicator on these devices show that there is no sound being received.

**Comment by aramg** [comment]
OK, thanks. I am attaching here (below) another test build with some more error logging added to test.
Could you try `./droidcam-cli -a 192.168.1.186 4747` & `./droidcam-cli -a adb 4747` and let me know if any errors are printed.

I do want to note, it really seems like there is a network misconfiguration either on the PC or the Phone system.
The error from earlier should not really happen for a local P2P connection that DroidCam does, and even if we can patch around it by increasing timeouts and other tweaks, in the end you'll probably keep seeing weird behaviour.

[droidcam_190_RC3.zip](https://github.com/dev47apps/droidcam/files/10936292/droidcam_190_RC3.zip)

**Comment by AndrewAmmerlaan** [comment]
Here's the wifi log:
```
andrew@andrew-gentoo-pc droidcam-dev % ./droidcam-cli -a 192.168.1.186 4747
Looking for v4l2 card: platform:v4l2loopback_dc
Opened /dev/video0, fd:3
Device /dev/video0 is 'Droidcam' @ platform:v4l2loopback_dc-000
vid_format->type                =1
vid_format->fmt.pix.width       =1920
vid_format->fmt.pix.height      =1080
vid_format->fmt.pix.pixelformat =842093913
vid_format->fmt.pix.sizeimage   =3110400
vid_format->fmt.pix.field       =1
vid_format->fmt.pix.bytesperline=1920
vid_format->fmt.pix.colorspace  =8
WEBCAM_W=1920, WEBCAM_H=1080
init audio
Trying /proc/asound/card0/id
Trying /proc/asound/card1/id
Trying /proc/asound/card2/id
Trying to open audio device: hw:2,0,0
spx_decoder.state=0x5599046f68d0, frame_size=320
decoder_init done
Client v1.9.0
Audio: hw:2,1,0
audio boost 100%
Audio Thread UDP try #0
audio keepalive
audio keepalive
^Cjoining
Audio Thread End
Cleanup
spx_decoder.snd_handle 0x559904707d00
spx_decoder.state=0x5599046f68d0
exit
```

And here's the adb log:
```
andrew@andrew-gentoo-pc droidcam-dev % ./droidcam-cli -a adb 4747
Looking for v4l2 card: platform:v4l2loopback_dc
Opened /dev/video0, fd:3
Device /dev/video0 is 'Dummy video device (0x0000)' @ platform:v4l2loopback-000
Opened /dev/video1, fd:3
Device /dev/video1 is 'Droidcam' @ platform:v4l2loopback_dc-000
vid_format->type                =1
vid_format->fmt.pix.width       =1920
vid_format->fmt.pix.height      =1080
vid_format->fmt.pix.pixelformat =842093913
vid_format->fmt.pix.sizeimage   =3110400
vid_format->fmt.pix.field       =1
vid_format->fmt.pix.bytesperline=1920
vid_format->fmt.pix.colorspace  =8
WEBCAM_W=1920, WEBCAM_H=1080
init audio
Trying /proc/asound/card0/id
Trying /proc/asound/card1/id
Trying /proc/asound/card2/id
Trying to open audio device: hw:2,0,0
spx_decoder.state=0x5632518398d0, frame_size=320
decoder_init done
Client v1.9.0
Audio: hw:2,1,0
Got line: List of devices attached
Got line: 17a33400      device
CheckAdbDevices rc=0
audio boost 100%
UDP didnt work, trying TCP
connect to 127.0.0.1:4747
- return fd: 4
^Cjoining
Audio Thread End
Cleanup
spx_decoder.snd_handle 0x56325184ad00
spx_decoder.state=0x5632518398d0
exit
```

However, the weirdest thing just happend. I wanted to test this on Windows to check if that exhibits the same problem,  both audio and video worked fine in the Windows client. Then I went back to Linux and all of a sudden both audio and video were working. I downgraded to the 1.8.2 release and somehow this was now working as well without problems. 

I am stumped, I tried this on two different computers, and two different networks and could reliably reproduce the problem. Then I connect it once through the Windows client and all of a sudden all the problems are gone? It makes no sense at all! I went back to the laptop where earlier I also had the same problem, and also here it works fine now. It is as if connecting it in Windows changed something in the connection or in the app that somehow fixed the problem I was having in Linux.

I'll play with this some more and let you know if I can break it again.

**Comment by aramg** [comment]
OK, thanks for the update and yes please let me know.

The logs look fine btw, it looks like over Wifi it used UDP as expected, and via adb it correctly switched to a TCP connection. No errors. 

I will hold the client update a few days for any potential changes.

**Comment by AndrewAmmerlaan** [comment]
The socket timeout issues is back, version 1.8.2 stopped working again. The return of the problem is just as random as its sudden disappearance. I didn't really change anything, all I really did was wait a couple of days and try again. Once again the 1.9.0_rc2 version fixes the problem. Though this time I cannot reproduce the issue that I had last time where the audio is not received. With version 1.9.0_rc2 and 1.9.0_rc3 both audio and video work fine, the log is identical to the one I sent before.  

I'm sorry that I can't be more precise, perhaps the audio problem I had before was a just a temporary pipewire hiccup?

**Comment by AndrewAmmerlaan** [comment]
Just had an online meeting again and droidcam worked flawlessly. Closing this issue.
