### ISSUE TITLE
Multiple Instances on desktop

### ISSUE THREAD

**Issue by iRoc999** [dev47apps/droidcam#243]
Hello if there isn't already or i missed it, but is there a possibility to get multiple instances up at the same time on =>Windows 10. So that multiple smartphones/tablets can be used as separate webcams at the same time.  

I have no issue running multiple cameras, but do not seem to be able to connect to more than one at a time on the desktop. Where as if multiple instances= True! then each instance could be set to the separate camera ip addresses.

This would be greatly appreciated! Great work so far

**Comment by aramg** [comment]
Parallel webcams are not supported on Windows. Transferring so much data through the system is very resource intensive and not recommended. 
 
* You can connect up to 3 phones to the Windows Client, but only 1 can be active at any time.
See "Can I use multiple phones at the same time" at https://www.dev47apps.com/droidcam/help/

* You can use DroidCam-OBS to get multiple feeds into OBS Studio simultaneously.
