### ISSUE TITLE
libusbmuxd was not found (Fedora 38)

### ISSUE THREAD

**Issue by gerraour** [dev47apps/droidcam#245]
I'm trying to install droidcam but stuck with libusbmuxd error when i try to make

cc  -Wall -O2 src/droidcam-cli.c src/connection.c src/settings.c src/decoder.c src/decoder_snd.c src/decoder_v4l2.c src/av.c src/usb.c src/queue.c -o droidcam-cli  `pkg-config --libs --cflags libswscale libavutil` `pkg-config --libs --cflags libturbojpeg` `pkg-config --libs --cflags libusbmuxd` -lspeex -lasound -lpthread -lm
Package libusbmuxd was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusbmuxd.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libusbmuxd', required by 'virtual:world', not found
/usr/bin/ld: /tmp/cc1WwDBf.o: in function `CheckiOSDevices':
usb.c:(.text+0x246): undefined reference to `usbmuxd_get_device_list'
/usr/bin/ld: usb.c:(.text+0x25b): undefined reference to `usbmuxd_connect'
/usr/bin/ld: usb.c:(.text+0x28e): undefined reference to `usbmuxd_device_list_free'
/usr/bin/ld: usb.c:(.text+0x2ab): undefined reference to `usbmuxd_device_list_free'
/usr/bin/ld: usb.c:(.text+0x2c3): undefined reference to `usbmuxd_device_list_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:61: droidcam-cli] Error 1

**Comment by aramg** [comment]
Sorry, I don't have access to my Linux env at the moment, but you can try replacing

`USBMUXD = pkg-config --libs --cflags libusbmuxd` with `USBMUXD = -lusbmuxd-2.0`  in the Makefile, as a temporary workaround.

**Comment by gerraour** [comment]
Solved the issue by changing the line to `USBMUXD = `pkg-config --libs --cflags libusbmuxd-2.0``

Thank you very much
