### ISSUE TITLE
I try to call a virtual camera using ROS on a Unix device, but I get an error, this process works fine on another x86_64 host, the same configuration

### ISSUE THREAD

**Issue by Bin-ze** [dev47apps/droidcam#246]
**Describe the bug**
I use the following command：

> uname -a
> Linux xbrain-orin-1 5.10.65-tegra #1 SMP PREEMPT Mon May 16 20:58:07 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux

>  v4l2-ctl -d /dev/video6 --all
> Driver Info:
	Driver name      : Droidcam
	Card type        : Droidcam
	Bus info         : platform:v4l2loopback_dc-000
	Driver version   : 5.10.65
	Capabilities     : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
Priority: 0
Video input : 0 (loopback: ok)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'YU12' (Planar YUV 4:2:0)
	Field             : None
	Bytes per Line    : 640
	Size Image        : 460800
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             : 
Streaming Parameters Video Capture:
	Frames per second: 30.000 (30/1)
	Read buffers     : 16
                    keep_format 0x08000000 (bool)   : default=0 value=0
              sustain_framerate 0x08000001 (bool)   : default=0 value=0
                        timeout 0x08000002 (int)    : min=0 max=100000000 step=1 default=0 value=0
               timeout_image_io 0x08000003 (bool)   : default=0 value=0

> cd droidcam/ && ./droidcam-cli 192.168.1.188 4747 -dev=/dev/video6 
Audio loopback device not found.
Is snd_aloop loaded?
Client v2.0.0
Video: /dev/video6

No problem here, the camera is functioning normally

but when run:
> roscd usb_cam/launch
> roslaunch usb_cam usb_cam-test.launch
      > log:
      ... logging to /home/xbrain-orin-1/.ros/log/cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0/roslaunch-xbrain-orin-1-25107.log
      Checking log directory for disk usage. This may take a while.
      Press Ctrl-C to interrupt
      Done checking log file disk usage. Usage is <1GB.
      started roslaunch server http://xbrain-orin-1:41205/
      SUMMARY
      ========
      PARAMETERS
       * /image_view/autosize: True
       * /rosdistro: noetic
       * /rosversion: 1.15.14
       * /usb_cam/camera_frame_id: usb_cam
       * /usb_cam/color_format: yuv422p
       * /usb_cam/image_height: 480
       * /usb_cam/image_width: 640
       * /usb_cam/io_method: mmap
       * /usb_cam/pixel_format: YU12
       * /usb_cam/video_device: /dev/video6
      NODES
        /
          image_view (image_view/image_view)
          usb_cam (usb_cam/usb_cam_node)
      auto-starting new master
      process[master]: started with pid [25115]
      ROS_MASTER_URI=http://localhost:11311
      setting /run_id to cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0
      process[rosout-1]: started with pid [25125]
      started core service [/rosout]
      process[usb_cam-2]: started with pid [25131]
      process[image_view-3]: started with pid [25133]
      [ INFO] [1682671003.763405548]: Initializing nodelet with 12 worker threads.
      [ INFO] [1682671003.819493218]: Using transport "raw"
      Unable to init server: Could not connect: Connection refused
      (image_raw:25133): Gtk-WARNING **: 16:36:43.824: cannot open display: 
      malloc(): smallbin double linked list corrupted
      [ INFO] [1682671003.839623958]: using default calibration URL
      [ INFO] [1682671003.840972525]: camera calibration URL: file:///home/xbrain-orin-1/.ros/camera_info/head_camera.yaml
      [ INFO] [1682671003.841135088]: Unable to open camera calibration file [/home/xbrain-orin-1/.ros/camera_info/head_camera.yaml]
      [ WARN] [1682671003.841186257]: Camera calibration file /home/xbrain-orin-1/.ros/camera_info/head_camera.yaml not found.
      [ INFO] [1682671003.841246386]: Starting 'head_camera' (/dev/video6) at 640x480 via mmap (YU12) at 30 FPS
      [FATAL] [1682671003.841299859]: Unknown pixel format 'YU12'
      [ERROR] [1682671003.843454903]: close error 9, Bad file descriptor
      [usb_cam-2] process has died [pid 25131, exit code 1, cmd /opt/ros/noetic/lib/usb_cam/usb_cam_node __name:=usb_cam __log:=/home/xbrain-orin-1/.ros/log/cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0/usb_cam-2.log].
      log file: /home/xbrain-orin-1/.ros/log/cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0/usb_cam-2*.log
      [image_view-3] process has died [pid 25133, exit code -6, cmd /opt/ros/noetic/lib/image_view/image_view image:=/usb_cam/image_raw __name:=image_view __log:=/home/xbrain-orin-1/.ros/log/cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0/image_view-3.log].
      log file: /home/xbrain-orin-1/.ros/log/cd3a2db0-e59f-11ed-bc99-48b02d7b7ba0/image_view-3*.log

Droidcam driver version on another device is different from above host：
> uname -a 
Linux desc-System-Product-Name 5.4.0-137-generic #154~18.04.1-Ubuntu SMP Tue Jan 10 16:58:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

> v4l2-ctl --list-formats-ext --all
> Driver Info (not using libv4l2):
	Driver name   : Droidcam
	Card type     : Droidcam
	Bus info      : platform:v4l2loopback_dc-000
	Driver version: 5.4.218
	Capabilities  : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
Priority: 0
Video input : 0 (loopback: ok)
Format Video Capture:
	Width/Height      : 1920/1080
	Pixel Format      : 'YU12'
	Field             : None
	Bytes per Line    : 1920
	Size Image        : 3110400
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Limited Range)
	Flags             : 
Streaming Parameters Video Capture:
	Frames per second: 30.000 (30/1)
	Read buffers     : 16
                    keep_format 0x08000000 (bool)   : default=0 value=0
              sustain_framerate 0x08000001 (bool)   : default=0 value=0
                        timeout 0x08000002 (int)    : min=0 max=100000000 step=1 default=0 value=0
               timeout_image_io 0x08000003 (bool)   : default=0 value=0
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'YU12'
	Name        : Planar YUV 4:2:0
		Size: Discrete 1920x1080
			Interval: Discrete 0.033s (30.000 fps)

**how can i solve this problem？**

**Comment by Bin-ze** [comment]
@suhr @eazel7 @okready @dLobatog 
Can you give me some advice?

**Comment by suhr** [comment]
> Can you give me some advice?

Yes: don't ping random people.

**Comment by aramg** [comment]
@Bin-ze - you can see the error is 
```
 [INFO] [1682671003.841246386]: Starting 'head_camera' (/dev/video6) at 640x480 via mmap (YU12) at 30 FPS
[FATAL] [1682671003.841299859]: Unknown pixel format 'YU12'
[ERROR] [1682671003.843454903]: close error 9, Bad file descriptor
```

This installation of "ROS" (I am not sure what that is, btw) seems to be having issues with the color format used by DroidCam.
You can try using the regular v4l2loopback device instead, but the color format set by the DroidCam client will still be the same.

This does not look like an issue with DroidCam itself ultimately.
