### ISSUE TITLE
API Basic 

### ISSUE THREAD

**Issue by Gamer1990** [dev47apps/droidcam#250]
i Would love for there to be a Basic Clear Cut Api the problem as i see  it is the Website is another Window on a Very limited limited Screen Size but after trying what  others have Saud its not working for those who are Working on  a multiple Camera it would take a whole Screen
What i have is curl "http://10.0.0.201:4747/cam/1/zoomout" and 
Nothing any idea or help Will be allot of help 

Another thing is i would love simplly put is a Way to bypass the Monthly Checks as with any Company if the Servers go down We Cannot Verify that we brought the Right To use the Software and it will Stop Working

**Comment by aramg** [comment]
The API is undocumented but can be extracted from the webpage
```
/cam/1/frame.jpg
/cam/1/takepic
/cam/1/af
/cam/1/led_toggle
/cam/1/zoomout
/cam/1/zoomin
```

You can call these end-points while the camera is active to execute the function.

**Comment by Gamer1990** [comment]
iam Trying to get this to work in a browser before i look at building a Custom app and its not working any idea why not ?

**Comment by aramg** [comment]
Sorry, this is not a support forum and what you are trying to do is outside the apps purpose (providing an API for custom apps).
Am closing this is off-topic.
