### ISSUE TITLE
Use phone zoom feature

### ISSUE THREAD

**Issue by Gauley123** [dev47apps/droidcam#251]
**Describe the feature you'd like to see added to the app**
I want it to be possible to use the phone's zoom feature because details look very grainy when I zoom with the current zoom feature

**Comment by Gamer1990** [comment]
I Totally Agree to some exist its going to be though because its getting a image and Digitally Zoom it but would be Cool

**Comment by aramg** [comment]
The app does not do any digital zoom or post-processing.
It uses the Phones zoom functionality via the Android camera APIs.
