### ISSUE TITLE
Linux no 90 degree rotate option

### ISSUE THREAD

**Issue by weezy20** [dev47apps/droidcam#253]
On windows we can do a 90 degree rotate but not on linux. Would love to see this feature added as my phone is much more simpler placed upright than horizontally.

**Comment by aramg** [comment]
See the last part under "HD Mode" at https://www.dev47apps.com/droidcam/linux/ 

You can also try the new client at: https://beta.droidcam.app/

**Comment by weezy20** [comment]
@aramg I wasn't able to get the new client to find my device but I tried the instructions in the first link. While I was able to get a vertical video (90 deg rotation), clicking on invert video freezes the video input. The fix I am following for now is to keep my phone inverted. Is there a better way?

**Comment by aramg** [comment]
Unfortunately there isn't a better way, this is a very long-standing issue (#213 #134 #128 ..).

The main problem are no simple ways to do this on Linux, only complex graphics libraries are available, requiring a lot of new code. The new client is the path forward, its based on OBS and takes advantage of the graphics processing already present there.

With the new client, after you click "Refresh Device List" 3 times, it will give you an option to add a device manually. Could you try that?
