### ISSUE TITLE
cant seem to install it

### ISSUE THREAD

**Issue by Adaaks** [dev47apps/droidcam#256]
trying to install droidcam on my neptune 4 to use my phone as webcam but keeping having issues some type of kernal issue. does anyone know how to resolve this. 

error: mks@mkspi:/tmp/droidcam$ sudo ./install-video
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/tmp/droidcam/v4l2loopback'
make -C /lib/modules/5.16.20-rockchip64/build M=/tmp/droidcam/v4l2loopback modules
make[1]: Entering directory '/tmp/droidcam/v4l2loopback'
make[1]:  /lib/modules/5.16.20-rockchip64/build: No such file or directory.  Stop.
make[1]: Leaving directory '/tmp/droidcam/v4l2loopback'
make:  [Makefile:8: all] Error 2
make: Leaving directory '/tmp/droidcam/v4l2loopback'

THE main error seems to be
make[1]: *** /lib/modules/5.16.20-rockchip64/build: No such file or directory.  Stop.

**Comment by aramg** [comment]
This seems like a support issue, not a bug/feature request.

(you are missing the linux-headers package for your system)
