### ISSUE TITLE
Permission error on Android 13

### ISSUE THREAD

**Issue by christophelec** [dev47apps/droidcam#257]
**Describe the bug**
When opening the Android application, instead of the regular Network info, I get a large blue message PERMISSION ERROR (see screenshot)
When following the permission error link, I get to the settings for the application, which shows that all permission asked have been granted.
Trying to connect to the phone, through USB or network, does not work anymore, from two different computers, while it was working a day ago.
![Screenshot_20230908_212713_Settings](https://github.com/dev47apps/droidcam/assets/4365804/4b0f094a-3476-43cb-b5ed-d1dd6ac14685)
![Screenshot_20230908_212558_DroidCamX](https://github.com/dev47apps/droidcam/assets/4365804/b3880afb-ba21-4afa-8cf5-2fd1eaaa3fb3)

**Expected behavior**
I expect the usual DroidcamX screen to show up, and my phone to be usable as a webcam as it was a day ago.

**Additional context**
I did not change any settings manually. There might have been a phone upgrade in the meanwhile though.

**Comment by aramg** [comment]
Could you please check if you have the latest update, v6.15.
That should fix the problem (issue is with Notifications permission on Android 13).

Note that app related requests should be directed at the support email.
