### ISSUE TITLE
F-droid publication

### ISSUE THREAD

**Issue by Astaoth** [dev47apps/droidcam#258]
Hi,

I've just discovered that Droidcam is an open source app. Will you be willing to publish it on F-droid for users which don't have the Gplay on their smartphones ? Or at least to provide the APK directly on the github releases ?

Kind regards

**Comment by aramg** [comment]
This is the Linux client, not the phone app.

The apk is readily available on PlayStore mirror sites, and a non-GMS version of the full app is available for purchase on the website.

**Comment by einarpersson** [comment]
Sorry if I misunderstand - so the phone-app is not open source?

I am trying to install this app using [Obtainium](https://github.com/ImranR98/Obtainium) (which I think is a fantastic app) but I can't get it to work.
