### ISSUE TITLE
Pixel format error

### ISSUE THREAD

**Issue by parantes** [dev47apps/droidcam#267]
I'm running droidcam version 1.9.0-1.4 on OpenSUSE Tumbleweed, installed from the distro repositories. The app was working fine until a couple of days ago. Now, when I try to start this application I get the error message below:  

Fatal: droidcam video device reported pixel format 34524742 (BGR4), expected 32315559 (YU12/I420)
Try 'v4l2loopback-ctl set-caps "video/x-raw, format=I420, width=640, height=480" /dev/video

Following the suggestion on the error message I tried the following, but the error message still persists and the app won't start.

> v4l2loopback-ctl set-caps /dev/video "UYVY:640x480@30/1"

Would appreciate any hints on how to solve the issue.

**Comment by RDKRACZ** [comment]
v4l2loopback-ctl set-caps /dev/video "YU12:640x480"

https://github.com/dev47apps/droidcam/issues/248#issuecomment-1587563387

**Comment by aramg** [comment]
The latest v2.1.x available here on Github should fix that. 
This will be made available generally in the next short while.
