### ISSUE TITLE
Support for EasyTether Pro and DroidCam to be used at the same time

### ISSUE THREAD

**Issue by japanesetelevision** [dev47apps/droidcam#275]
**Describe the feature you'd like to see added to the app**

I am on Arch Linux and I would really appreciate it if support for both to be used at the same time could be implemented because at the moment I am only able to use one or the other. When I try to use DroidCam with EasyTether Pro DroidCam says that no devices are found. I also tried starting EasyTether Pro first but that didn't work either. Any help would be appreciated.

**Comment by aramg** [comment]
Please use support@dev47apps.com for support inquiries.
