### ISSUE TITLE
DroidCam OBS Plugin for Linux doesn't pick the right version

### ISSUE THREAD

**Issue by cybik** [dev47apps/droidcam#279]
**Describe the bug**
Droidcam OBS refuses to initialize if libavcodec60 is installed, even if libavcodec59 is present.
![Both installed.](https://github.com/dev47apps/droidcam/assets/387759/0ddb8d3d-81e6-4f5e-bfc3-c239126b10c4)

**Expected behavior**
droidcam-obs would detect that 59 is indeed installed even though 60 is present, and load the right version.

**Additional context**
libavcodec60 is a system dependency here. If I try to uninstall it to just keep 59, half my system goes with it.
![kablooie](https://github.com/dev47apps/droidcam/assets/387759/ff115d07-d435-4556-81e8-0b786e704240)

**Comment by cybik** [comment]
Adding here that OBS itself is linked against libavcodec60 on my system, which leads me to assume droidcam-obs would piggyback on OBS' already-loaded library.

That'll probably make it hard to use 59?

**Comment by aramg** [comment]
Please follow the Linux instructions for the plugin, https://github.com/dev47apps/droidcam-obs-plugin/wiki/Linux-Releases
You need to download the correct release for your ffmpeg version, libavcodec60 in this case
