### ISSUE TITLE
Missing rotation/flipping options

### ISSUE THREAD

**Issue by aramg** [dev47apps/droidcam#38]
Investigate using avfilter.

https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/filtering_video.c
http://ffmpeg.org/ffmpeg-filters.html

**Comment by sebastiandg7** [comment]
+1 For this!!

**Comment by aramg** [comment]
AVFilter did not really work to my satisfaction.
next candidate is SDL, then OpenGL

**Comment by gnumoksha** [comment]
I think dev47apps.com should mention that these features don't work on GNU/Linux yet; I bought  droidcam in order to use they.

**Comment by aramg** [comment]
There is a note under the Install section of the Linux age. If you email dev47apps at gmail with your order info, we can sort that out.

**Comment by guerra08** [comment]
+1, would really like this feature!

**Comment by marcodotsh** [comment]
#120

**Comment by AvverbioPronome** [comment]
This is a feature that can probably be moved from the PC client to the Android app.  I think.

**Comment by aramg** [comment]
With the latest release, its now possible to achieve both 90º (by flipping the webcam Width|Height), and 180º (Vertical flip (Ctrl+V) video. 

Closing this, let me know if there are still issues.

**Comment by rudilee** [comment]
I'm sorry if I misunderstood the instruction, I try to flip the width & height by setting the `size` option like: `droidcam -size=720x1280`, it doesn't make it rotate at all, is it the correct way to do it?

**Comment by aramg** [comment]
That is correct, though I'm not sure if the regular v4l2loopback module works the same way (it should).
You can try `ffplay /dev/videoX` and see what the output resolution from the webcam is coming as.
The instructions for DroidCam assume v4l2loopback-dc is used.

**Comment by sahilrajput03** [comment]
I a using v4l2loopback-dc only and my back cam and front cam are both rotated by 90 degrees. :( Please make way to solve my issue ...

**Comment by sahilrajput03** [comment]
I did try both vertical flip and horizontal flip but nohting solves my rotate problem.. !
Please address this..!

**Comment by sahilrajput03** [comment]
> That is correct, though I'm not sure if the regular v4l2loopback module works the same way (it should).
> You can try `ffplay /dev/videoX` and see what the output resolution from the webcam is coming as.
> The instructions for DroidCam assume v4l2loopback-dc is used.

![](https://i.imgur.com/T11FFbU.png) Thats how it is, the right window is `ffplay`.
This shows that

**Comment by aramg** [comment]
This is not a support @sahilrajput03, you'll need to email support@dev47apps.com.
Please include the Terminal output of ffplay, not the video.

**Comment by sahilrajput03** [comment]
> This is not a support @sahilrajput03, you'll need to email [support@dev47apps.com](mailto:support@dev47apps.com).
> Please include the Terminal output of ffplay, not the video.

Just did a mail there to look here at this issue !
Thanks.
Though, i am still using droidcam inspite of this rotation thing, but adding the cam in **OBS studio**, i can rotate the video input there very easily!! 

I would recommend other people to use "OBS Studio" and use rotate feature there. For my setup,  i get to cast to youtube stream and OBS studio is pretty comfortable with a whole lot such things. [This](https://www.digitaltrends.com/computing/how-to-live-stream-on-youtube-with-obs/) is a very fair example on how to use youtube streaming with OBS studio, I just love it.

**Comment by sahilrajput03** [comment]
i just received email and it says:

```
Hi,

If I'm reading you comment on the issue correctly, you are trying to
apply a 90º rotation?
See the last paragraph under "HD Mode" section here on how to do that
https://www.dev47apps.com/droidcam/linux/

Note that on Linux, the image rotation and flipping facilities are
pretty basic due to lack of good graphics libraries on the os.

```
soon i am gonna try this as i still need to rotate the camera in my obs software always.

anybody wanna try please follow the above email's instructions. 🤾🏾‍♀︎🤾🏾‍♀︎

**Comment by ezxpro** [comment]
> With the latest release, its now possible to achieve both 90º (by flipping the webcam Width|Height), and 180º (Vertical flip (Ctrl+V) video.
> 
> Closing this, let me know if there are still issues.

Your advice is assuming one is using a Windows client. None of that works on Linux

**Comment by BeholdersEye** [comment]
Incredibly frustrating that the free version of this software rotates the video 90 degrees just to display a disabled "Rotate video" button next to a "Buy the pro version to unlock PRO CONTROLS!" 

💸🗑️
