### ISSUE TITLE
Two instances of Droidcam

### ISSUE THREAD

**Issue by thiagopaixao** [dev47apps/droidcam#90]
Hello.
I compiled and installed the droidcam on a Raspberry Pi 3, it works well for a camera, but I would like to use two smartphones as cameras.

I can run the droidcam twice and connect to different cell phones, but both instances access the device / dev / video0, and the images are superimposed.

How to run a second instance on another device / dev / video1 for example?

**Comment by aramg** [comment]
Parallel webcams arent supported right now, you might be able to hack something together, but as of now the only way to get multiple phones is via the `http://...` MJPG source.

**Comment by ShockedCoder** [comment]
I guess there could be an `advanced options` tab in the future for advanced users that want to specify the path to the camera, but then you'd need to make the video paths with `v4l2loopback`. Just throwing some ideas around.

**Comment by aramg** [comment]
Yes, an option to use a specific video device and instead of calling find_v4l2_device(), add a 'open_v4l2_device(..)' function to decoder_v4l2.c and use that. Adding the option to the cli client would be super simple, the GUI client a little less so. Maybe something via the config file.

**Comment by aramg** [comment]
Added to v1.7 via 7d07b7fda4a8ae9679ae25637eb1d180bfe934a2
