### ISSUE TITLE
IOS usb connection : connection reset, is the app running

### ISSUE THREAD

**Issue by mfauvain** [dev47apps/droidcam#97]
Hi, using droidcam on linux kernel 5.8 and ios. Works fine using wifi connection but not using USB.
When using USB the app on iphone briefly shows the live video and 1s later I have :
`Error: Connection reset!`
`Is the app running?`

Am I missing something obvious?
Thx

**Comment by marcelroed** [comment]
I'm having the same issue, running Arch Linux with kernel 5.9 and iOS 14.1. After simply connecting the iPhone via USB, selecting USB (iOS) and clicking start, I get an error asking if the app is running.

![image](https://user-images.githubusercontent.com/13435604/97823179-1362dc80-1cb0-11eb-80ee-322b4c0fa54a.png)

The phone app flashes as if something is about to happen, but then goes back to the idle state.

Some love for this issue would be much appreciated!

**Comment by aramg** [comment]
hmm, not sure. Can you guys try using `iproxy` (part of either usbmuxd or usbmuxd-tools package) to create a local proxy and connect like that? Does it work?

Your version of iproxy might have different usage, but roughly 
```
$ iproxy -h
iproxy [LOCAL_TCP_PORT] [DEVICE_TCP_PORT] [UDID]
$ iproxy 1111 4747
$ droidcam-cli localhost 1111
```
via http://manpages.ubuntu.com/manpages/trusty/man1/iproxy.1.html

**Comment by marcelroed** [comment]
Here's what I get (Arch):

![image](https://user-images.githubusercontent.com/13435604/97911518-4ace9900-1d43-11eb-85af-d1a092dbe1dd.png)

**Comment by aramg** [comment]
Can you replace `localhost` with `127.0.0.1`
Whats the output of `netstat -nltp`

**Comment by marcelroed** [comment]
Replacing `localhost` with `127.0.0.1` does the trick!

![image](https://user-images.githubusercontent.com/13435604/97912626-f6c4b400-1d44-11eb-9d42-2171d75fe05f.png)

**Comment by aramg** [comment]
Nice, but the droidcam built-in connection option still breaks?
Weird because AFAIK it does exactly what iproxy does :/

Amy chance its the USB port or cable that's questionable?

**Comment by marcelroed** [comment]
Yeah, it still breaks for some reason. I tried the same setup with my brand new iPad and it had the exact same problem, so I don't think it's the cable. It could be the USB controller on the PC I guess, but I haven't had any other issues with it.

**Comment by aramg** [comment]
There is only 1 line of code I see that might cause this behaviour in usbmuxd.
Can you try the attached build
[droidcam-cli.zip](https://github.com/aramg/droidcam/files/5477801/droidcam-cli.zip)

**Comment by marcelroed** [comment]
I overwrote the existing droidcam-cli file and ran it, resulting in

```
$ /usr/bin/droidcam-cli
/usr/bin/droidcam-cli: error while loading shared libraries: libusbmuxd.so.4: cannot open shared object file: No such file or directory
```

**Comment by aramg** [comment]
Right, yes, take 2:
[droidcam-cli.zip](https://github.com/aramg/droidcam/files/5477846/droidcam-cli.zip)

**Comment by marcelroed** [comment]
Brilliant! That works using
```
droidcam-cli ios 4747
```

**Comment by aramg** [comment]
haha, great. I'll make a note to update the client with this change.
I guess different versions of usbmuxd have this alternate behaviour
```
 $ git diff
-       usbmuxd_device_list_free(&deviceList);
+       //usbmuxd_device_list_free(&deviceList);

**Comment by Janhouse** [comment]
@aramg, I still get the issue in v1.6.

Using `iproxy 1111 4747` and then `droidcam-cli 127.0.0.1 1111` works, but connecting directly doesn't, same error as reported before:

```
Error: Connection reset!
Is the app running?
```

Using the previously attached `droidcam-cli.zip` works just fine.

I thought that maybe 1.6 was released from wrong branch but I compiled master from source and it has the problem.

**Comment by marcelroed** [comment]
@Janhouse Yep, same issue. I'm just using the version from droidcam-cli.zip instead.

**Comment by aramg** [comment]
> @aramg, I still get the issue in v1.6.
>
> I thought that maybe 1.6 was released from wrong branch but I compiled master from source and it has the problem.

hmm, could you `git revert 5dfdd9551ae0542289d312ba682add03143b00c2` then make this change in `src/usb.c` CheckiOSDevices()
```
-       usbmuxd_device_list_free(&deviceList);
+       //usbmuxd_device_list_free(&deviceList);

**Comment by Janhouse** [comment]
That did not help, same problem.

After showing the error on Linux, iOS app flashes black for ~100ms and then goes back to the default screen where it shows IP and port.

Could it be that the problem comes from the linked libs or something else in the build process?

Here are the params that are used on Archlinux to build it: `make JPEG_DIR="" JPEG_INCLUDE="" JPEG_LIB="" JPEG=$(pkg-config --libs --cflags libturbojpeg) USBMUXD=-lusbmuxd-2.0`

And here are the linked libs:

```
ldd droidcam-cli 
	linux-vdso.so.1 (0x00007fff04fe9000)
	libturbojpeg.so.0 => /usr/lib/libturbojpeg.so.0 (0x00007feb3f43e000)
	libswscale.so.5 => /usr/lib/libswscale.so.5 (0x00007feb3f3ae000)
	libavutil.so.56 => /usr/lib/libavutil.so.56 (0x00007feb3f0f9000)
	libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007feb3f0de000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x00007feb3efff000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007feb3efdd000)
	libusbmuxd-2.0.so.6 => /usr/lib/libusbmuxd-2.0.so.6 (0x00007feb3efce000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007feb3edf1000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007feb3ecab000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007feb3ec91000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007feb3eac8000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007feb3f543000)
	libva-drm.so.2 => /usr/lib/libva-drm.so.2 (0x00007feb3eac3000)
	libva.so.2 => /usr/lib/libva.so.2 (0x00007feb3ea94000)
	libva-x11.so.2 => /usr/lib/libva-x11.so.2 (0x00007feb3ea8c000)
	libvdpau.so.1 => /usr/lib/libvdpau.so.1 (0x00007feb3ea87000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007feb3e946000)
	libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007feb3e931000)
	libmfx.so.1 => /usr/lib/libmfx.so.1 (0x00007feb3e923000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007feb3e91b000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007feb3e910000)
	libplist-2.0.so.3 => /usr/lib/libplist-2.0.so.3 (0x00007feb3e8fd000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007feb3e8e8000)
	libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007feb3e8df000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007feb3e8b3000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007feb3e8ae000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007feb3e8a6000)
```

Currently Archlinux has libusbmuxd version 2.0.2-1

**Comment by Janhouse** [comment]
Oh, and on iOS the green indicator in status bar shows up for a second (indicating camera usage)

**Comment by aramg** [comment]
Could be the release build, I use an older Ubuntu 16 VM for that.
How do the linked libs compare to the zip in this thread, the one that works?

**Comment by Janhouse** [comment]
It appears to have some of those libs statically linked since they don't show up in list.

```
ldd droidcam-cli 
	linux-vdso.so.1 (0x00007ffd825c7000)
	libspeex.so.1 => /usr/lib/libspeex.so.1 (0x00007f1c8a2d8000)
	libasound.so.2 => /usr/lib/libasound.so.2 (0x00007f1c8a1f9000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1c8a1d7000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1c89ffa000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f1c89eb4000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1c89e9a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f1c89ccf000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1c89cc9000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f1c89cbe000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1c8a33c000)
```

**Comment by aramg** [comment]
Whats I'm not sure about is even if you build from master yourself, it doesn't work?
The code looks fine from what I can tell, unless I'm missing something obvious.

There _is_ a difference between libusbmuxd versions on Ubuntu 16 (build VM)  and 19 (dev VM), here is a release build (current master branch) compiled against the newer lib
https://www.dev47apps.com/files/linux/droidcam_1605382871.zip

Could you give it a try when you have a minute, please.

**Comment by DeadMetaler** [comment]
Installed 1.6 from AUR in Arch Linux and can't connect via USB. It uses GitHub's zip.
Installed 1.6 from https://files.dev47apps.net/linux/droidcam_latest.zip and all works via USB.

**Comment by Toxblh** [comment]
Same problem. All works good with iproxy and bin from the site. 
And yes https://pkgs.org/search/?q=libusbmuxd for Ubuntu 16 is latest is 1.0.10 version in Arch latest is 2.0.2 and need to jump to deep for understand the changes between version 1 and 2.

**Comment by alxjsn** [comment]
I'm having this issue using AUR vs the pre-built binaries as well.
